### ISSUE TITLE
[Anon] Bug report: Imperium - FW Death Korps of Krieg.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9381] opened 2021-02-04 04:52 UTC
**File:** Imperium - FW Death Korps of Krieg.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Death korps grenadier special weapons are constantly saying that sniper rifles must be equipped, and only sniper rifles may be equipped to not have any roster errors.

**Comment by Technoblazed** [comment] 2021-02-04 06:09
Duplicate of #9342

**Closed as completed by Technoblazed** 2021-02-04 06:09 UTC
