### ISSUE TITLE
[Anon] Bug report: Imperium - Imperial Knights.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11235] opened 2022-05-20 01:35 UTC
**File:** Imperium - Imperial Knights.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** 2K GT Knights (Warhammer 40,000 9th Edition v216) has 1 too many selections of Knight Baron (maximum 1).
-This should be maximum 2 when choosing a Strike Force sized mission and maximum 3 when choosing an onslaught mission

Warlord Trait: Cunning Commander is refunding 1CP when it should be no cost.

**Comment by AbonShell** [comment] 2022-05-20 03:42
Duplicate of #11226 & #11230

**Closed as completed by AbonShell** 2022-05-20 03:42 UTC
