### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#402] opened 2017-06-23 15:49 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.03

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Hive Tyrant's Wings should take up a weapon slot. It doesn't. With or without Wings it still requires 2 weapon slots to be filled.

**Comment by USSX-Hares** [comment] 2017-06-23 15:51
Duplicate of #401

**Closed as completed by USSX-Hares** 2017-06-23 15:51 UTC
Labels: ✔ Res: duplicate, Area: selections, 💾 Cat: Tyranids
