### ISSUE TITLE
Astra Militarum - Guardsman W/ Special Weapon limited to Snipers

### ISSUE THREAD

**Issue by CaptainJin** [BSData/wh40k-9e#9380] opened 2021-02-04 03:35 UTC
**File/Catalogue:** Imperium - Astra Militarum v296

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Guardsman W/ Special Weapon are restricted to only Sniper Rifles

**Comment by CaptainJin** [comment] 2021-02-04 03:36
This also happens to Veterans w/ Special Weapons

**Comment by Valorcalls** [comment] 2021-02-04 03:36
Duplicate of #9342

**Closed as completed by Valorcalls** 2021-02-04 03:37 UTC
