### ISSUE TITLE
Tyranids - Genestealer Cults: AoO Relic strat missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12257] opened 2023-01-16 09:13 UTC
**File:** Tyranids - Genestealer Cults.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Unable to use relic stratagem under AoO rules. Stratagem is present under nephilim, disappears when switching to AoO.

**Comment by AbonShell** [comment] 2023-01-29 11:59
duplicate of #12216

**Closed as completed by AbonShell** 2023-01-29 11:59 UTC
Labels: 💾 Cat: Tyranids - Genestealer Cults
