### ISSUE TITLE
Imperium- Agents of the Imperium Missing Options

### ISSUE THREAD

**Issue by gothmogbalrog** [BSData/wh40k-9e#7979] opened 2020-08-17 07:20 UTC
**File/Catalogue:** astra Militarum v283

**BattleScribe version:** 2.03.35.338

**Platform:** Android

**Dropbox:**  No

**Description:** Detailed issue description.
Agents of the Imperium in several Imperial Armies (checked Custodes, astra mil, blood Angels and DKK) are missing Inquisitor Hector Rex and Inquisitor Solomon Lok under "Agents of the Imperium" options. They both have the required "Inquisitor" keyword required by the "authority of the inquisition" rule to be added like any other inquisitor and both have current points on the Munitorum field manual.

**Comment by Technoblazed** [comment] 2020-08-17 07:31
Duplicate of https://github.com/BSData/wh40k/issues/7785. Neither of the two listed Inquisitors have the `AGENTS OF THE IMPERIUM` keyword.

**Closed as completed by Technoblazed** 2020-08-17 07:31 UTC
Labels: ✔ Res: invalid, Area: text/rule/profile, Type: bug

**Comment by gothmogbalrog** [comment] 2020-08-17 07:43
No one has that keyword. 

![15976501657834486783154290843778](https://user-images.githubusercontent.com/30101040/90370655-be61e380-e03b-11ea-98f9-3ef0ae18a8aa.jpg)

**Comment by gothmogbalrog** [comment] 2020-08-17 07:43
The rule for inquisitors is triggered by INQUISITOR   keyword.
![15976502205875868733913499216298](https://user-images.githubusercontent.com/30101040/90370731-dd607580-e03b-11ea-9dab-92a553f4dc91.jpg)

**Comment by gothmogbalrog** [comment] 2020-08-17 07:46
And the rules for asians is triggered off a stratagem and the Officio assanorium keyword
![img_9012](https://user-images.githubusercontent.com/30101040/90370905-257f9800-e03c-11ea-8059-acdc513520c2.jpg)

**Comment by Technoblazed** [comment] 2020-08-17 07:48
Please read the full issue that I linked in the previous post, it covers all you need to know.

**Comment by gothmogbalrog** [comment] 2020-08-17 07:48
Assassins also dont Have an "AGENTS OF THE IMPERIUM" keyword.

It's not a keyword. It's just the wall you all structured the BS catalogs.

So please add Rex and Lok. They have legal rules and the required keywords to be taken

![15976504418057446929399671113821](https://user-images.githubusercontent.com/30101040/90371054-611a6200-e03c-11ea-8397-79b39a6f6fc3.jpg)

**Comment by Technoblazed** [comment] 2020-08-17 07:50
The datasheets you have provided are outdated as of the release of Psychic Awakening: Pariah.

**Comment by gothmogbalrog** [comment] 2020-08-17 07:55
Read the other file.

Freaking Pariah. Rgr. Dumb AF. Emailing FAQ team.

Would technically the WD rules still apply to them seeing as they aren't in Pariah though. Like they'd still fall under Index:Inquisition. Not Agents of the Imperium then. And should then just be available under "no force org".

**Comment by Technoblazed** [comment] 2020-08-17 07:57
With the rule having the exact same name and it being an intentional change, it'll be across the board. The new IA books are *supposedly* dropping before the end of the year, so best bets is maybe they fix them then.
