### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8653] opened 2020-11-04 16:47 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** Redemptor Dreadnought Macro Plasma Incinerator special rule for overcharging is incorrect. Seems to be present across all SM factions.

Rule currently states: Blast. If any unmodified hit rolls of 1 are made for attacks with this weapon profile, the bearer is destroyed after shooting with this weapon.

Rule should state: Blast. Each time an unmodified hit roll of 1 is made for an attack with this weapon profile, the bearer suffers 1 mortal wound after shooting with this weapon.

Apologies if this is duplicate, couldn't see it in closed issues.

**Comment by Mad-Spy** [comment] 2020-11-04 16:53
Duplicate of #8652

**Closed as completed by Mad-Spy** 2020-11-04 16:53 UTC
