### ISSUE TITLE
Aeldari - Craftworlds - Relics are bugged

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8253] opened 2020-10-04 14:08 UTC
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** Remnants of Glory selections do not work as expected for all characters in Aeldari forces that can take them. Select for example Autarch with Swooping Hawk Wings that comes with a Power Sword as an option, then opts to "upgrade" the Power Sword with either the Firesabre or the Shard of Anaris (both requiring a model to have a Power Sword), the authentication then states the user has 1 too many selections of Power Sword (as these are both ALSO power swords but are meant to exist alongside the existing selection), if you de-select the Power Sword to try and resolve the error it then states you cannot have the Firesabre or Shard of Anaris as the model does not have the requisite Power Sword to take the upgrade.

This issue also applies to other Remnants of Glory that directly replace a standard equipment item, such as Kurnous' Bow replacing the Shuriken Pistol on a Warlock, taking the Bow causes a 1 too many Shuriken Pistol error and removing the pistol causes a can't take the Bow because no pistol error.

**Comment by FarseerVeraenthis** [comment] 2020-10-04 19:02
Duplicate of #8235 and #8236 
Sorry for the hiccup but it is fixed in the next release of the data.

**Closed as completed by FarseerVeraenthis** 2020-10-04 19:02 UTC
Labels: ✔ Res: duplicate, Area: selections, ✔ Res: merged, 💾 Cat: Aeldari - Craftworlds, Area: validation, Type: bug
