### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum - Library.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9368] opened 2021-02-01 20:54 UTC
**File:** Imperium - Astra Militarum - Library.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Astra Militarum guardsmen/veterans with Special Weapons produce an error stating that they must have Sniper Rifle selected whenever they are equipped with any other Special Weapon.  They should be allowed to have the other Special Weapons selected without error.  Thanks.

**Comment by Technoblazed** [comment] 2021-02-01 21:09
Duplicate of https://github.com/BSData/wh40k/issues/9342

**Closed as completed by Technoblazed** 2021-02-01 21:09 UTC
