### ISSUE TITLE
[Anon] Bug report: Imperium - Iron Hands.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8051] opened 2020-08-28 18:19 UTC
**File:** Imperium - Iron Hands.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** When I add a Relic Leviathan Dreadnought to my army and select the "March of the Ancients" stratagem, no field pops up to allow me to select it as my Warlord. I don't know if I'm doing anything wrong or if there is a step I am missing, or if it is simply something wrong with the system. The March of The Ancients successfully gives it the "Character" keyword, but there is no way to make it my warlord.
Thank you!

**Comment by Technoblazed** [comment] 2020-08-29 04:37
Duplicate of https://github.com/BSData/wh40k/issues/8022.

**Closed as completed by Technoblazed** 2020-08-29 04:37 UTC
Labels: ✔ Res: duplicate
