### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11490] opened 2022-06-28 17:44 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** When selecting warlord traits as Grey Knights, if you select the Shield of Humanity option on a character to select a warlord trait as a non-warlord character the warlord traits do not appear on the data sheet.

**Comment by tekton** [comment] 2022-06-28 17:55
Duplicate of #11425 - fixed in next release!

**Closed as completed by tekton** 2022-06-28 17:55 UTC
