### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8968] opened 2020-12-05 12:09 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** In new "Emperial Armor" book tarantula battery is cost 40 points with twin heavy bolter and 50 points with twin lascannon. But in "battle scribe" it is cost 50 points with twin heavy bolter and 60 with twin lascannon.

**Comment by Valorcalls** [comment] 2020-12-05 23:19
duplicate of #8969

**Closed as completed by Valorcalls** 2020-12-05 23:19 UTC
