### ISSUE TITLE
[Anon] Bug report: Necrons.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12431] opened 2023-02-03 09:55 UTC
**File:** Necrons.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** In Necrons lists, it only allows for one Canoptek Plasmacyte in the No Force Org Slot, however you can have one for each Destroyer Unit in the list according to the Viral Construct rule on the Plasmacyte.

**Comment by Mad-Spy** [comment] 2023-02-03 09:58
Duplicate of #12379

**Closed as completed by Mad-Spy** 2023-02-03 09:58 UTC
