### ISSUE TITLE
Tome of Malcador doesn't allow power from dif. Discipline

### ISSUE THREAD

**Issue by corrinavatan** [BSData/wh40k-9e#9063] opened 2020-12-20 15:36 UTC
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** windows and android

**Dropbox:** Yes/No

**Description:**The wording of the Tome of Malcador in the 9e codex states that the bearer can know an additional power from "any discipline it has access to".

However, in Battlescribe, selecting a power from any discipline seems to "lock" you into selections just from that single discipline: if I select Xenopurge for my first power, the Obscuration powers are hidden for a Phobos Librarian, only allowing me to take Xenopurge discipline powers.

If I select an Obscuration power first, the Xenopurge powers are not hidden, but if I select a Xenopurge power I get an error stating that the Phobos Libby cannot take any Obscuration powers.

Was replicated using Deathwatch Phobos Librarian, taking Tome of Malcador relic, attempting First to take 2 Obscuration powers and 1 Xenopurge, then attempting instead to take 2 Xenopurge and 1 Obscuration, the first of which generated an error, the second of which wasn't possible as the Obscuration powers were removed when selecting Xenopurge first

**Comment by Technoblazed** [comment] 2020-12-20 15:37
Duplicate of the following:

https://github.com/BSData/wh40k/issues/7028
https://github.com/BSData/wh40k/issues/9006
https://github.com/BSData/wh40k/issues/8975
https://github.com/BSData/wh40k/issues/8974
https://github.com/BSData/wh40k/issues/8718
https://github.com/BSData/wh40k/issues/8619
https://github.com/BSData/wh40k/issues/7608

**Closed as completed by Technoblazed** 2020-12-20 15:37 UTC

**Comment by Dunamis55** [comment] 2020-12-20 15:40
For reference, this is working as intended, as detailed in the listed duplicate issues above. Please email GW's 40k FAQ team if you think it's incorrect.

**Comment by corrinavatan** [comment] 2020-12-20 15:42
Dunamis55,

I have to say I disagree with the interpretation.

What is the logic that the power granted by the Tome of Malcador must be from the same discipline, when the Tome itself states the power can be "from any discipline it has access to?"

**Comment by alphalas** [comment] 2020-12-20 15:44
The logic is a librarian only has access to one tree once he take a power from it, as spelled out in the codex. Tome doesn’t specifically override that.

**Comment by alphalas** [comment] 2020-12-20 15:45
If you wish to argue it further, take it to the discord. This is not the place for discussion.

**Comment by corrinavatan** [comment] 2020-12-20 15:45
Except it does.  "From ANY discipline it has access to" is a specific
override.

**Comment by alphalas** [comment] 2020-12-20 15:46
Locking.
