### ISSUE TITLE
Imperium Astra Militarum: Chimera max error

### ISSUE THREAD

**Issue by Viper666-Qc** [BSData/wh40k-9e#92] opened 2017-06-16 23:13 UTC
**File/Catalogue:** Imperium Astra Militarum
**BattleScribe version:** 2.01.
**Platform:** Windows
**Dropbox:** Yes
**Description:** When selecting 2 Chimeras, I get : Dedicated Transports has 1 too many selections of Chimeras (even if I already have many other elites/troops/hq choices taken)

**Comment by alphalas** [comment] 2017-06-16 23:30
duplicate of #6 - please look over #6 before you report more AM bugs ;)

**Closed as completed by alphalas** 2017-06-16 23:30 UTC
Labels: ✔ Res: duplicate, 💾 Cat: Imperium - Astra Militarum, Area: validation
