### ISSUE TITLE
Imperium - Astra Militarum: Issue with transport validation

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#62] opened 2017-06-16 18:08 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Error appears when selecting two taurox. "Dedicated transport have one too many selections of taurox (maximum 1)

This occurs when three troop slots have been selected.

**Comment by alphalas** [comment] 2017-06-16 20:49
duplicate of #6

**Closed as completed by alphalas** 2017-06-16 20:49 UTC
Labels: ✔ Res: duplicate, 💾 Cat: Imperium - Astra Militarum, Area: validation
