### ISSUE TITLE
[Anon] Bug report: Imperium - Adeptus Custodes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8959] opened 2020-12-04 17:05 UTC
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.22

**Platform:** Windows

**Dropbox:** No

**Description:** The relic selection is not being shown for shield captain jetbikes unless they are selected as the warlord.
Steps to reproduce:
1- Form a new army
2- Add the required HQ units (Include a shield captain in dawneagle jetbike)
3- Choose the non jetbike HQ as the warlord
4- Check the information for the non character HQ unit to add a relic to their gear
Result: The relics are not listed for the character
Expected: The relic option should be select-able for the unit as no unit has a relic already and its not a named character.

**Comment by Mad-Spy** [comment] 2020-12-04 18:34
Duplicate of #8956

**Closed as completed by Mad-Spy** 2020-12-04 18:34 UTC
