### ISSUE TITLE
blood angels Judicar listed under HQ instead of elites

### ISSUE THREAD

**Issue by hoaass** [BSData/wh40k-9e#7538] opened 2020-07-27 17:50 UTC
**File/Catalogue:** 
Imperium - Adeptus Astartes - Blood Angels
**BattleScribe version:** 
v2.03.25.338 for android
V2.03.15 for iPad
**Platform**
Android and iPad
**Dropbox:** 
No
**Description:** 
For the Blood Angels the Judicar it can only be added as an HQ but it should be an elite. 

For roster validation it seems to count the Judicar as both an elite and HQ. If I use a battalion and put in 6 elites and 3 HQs when I add the Judicar as an HQ I get errors that I am now over the limit on HQ and Elite slots.

**Comment by Dunamis55** [comment] 2020-07-27 17:53
Duplicate of #7427

**Closed as completed by Dunamis55** 2020-07-27 17:53 UTC
