### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8892] opened 2020-11-25 00:38 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Captain in Terminator Armour: when two lightning Claws selected a warning reading 1 too many selections of Lightning Claws (maximum 1). Two Lightning Claws are Legal per Space Marine Codex, Roster Error warning should not appear.

**Comment by Mad-Spy** [comment] 2020-11-25 08:22
Duplicate of #8803

**Closed as completed by Mad-Spy** 2020-11-25 08:22 UTC
Labels: 💾 Lib: Imperium - Space Marines
