### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11772] opened 2022-08-15 05:17 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When you select a Chaplain Venerable Dreadnought as your warlord, you can select the stratagems to give it warlord traits when it is currently eligible for them.

Add a Chaplain Venerable Dreadnought to your HQ. Select
it as your warlord. You should be able to spend CP to give it a warlord trait.

**Comment by Mad-Spy** [comment] 2022-08-16 12:17
Duplicate of #11518

**Closed as completed by Mad-Spy** 2022-08-16 12:17 UTC
