### ISSUE TITLE
[Anon] Bug report: Imperium - Inquisition.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8050] opened 2020-08-28 02:22 UTC
**File:** Imperium - Inquisition.catz

**BattleScribe version:** 2.03.21

**Platform:** Mac

**Dropbox:** No

**Description:** Lord Inquisitor Kyria Draxus's WS is incorrectly listed as 3+. Her correct WS is 2+.

**Comment by Mad-Spy** [comment] 2020-08-29 09:09
Duplicate of #8021

**Closed as completed by Mad-Spy** 2020-08-29 09:09 UTC
