### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7444] opened 2020-07-27 06:58 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Pts values are updated but no Indomitus models in Wolves roster files yet

**Comment by Mad-Spy** [comment] 2020-07-27 06:58
Duplicate of #7430

**Closed as completed by Mad-Spy** 2020-07-27 06:58 UTC
