### ISSUE TITLE
Power Levels for skitarii

### ISSUE THREAD

**Issue by kixxurazz** [BSData/wh40k-9e#11133] opened 2022-04-14 00:06 UTC
**Describe the bug**
The power levels reflected in the 9th edition battlescribe are off for skitarii rangers and vanguards (BS shows them as 3) and serberys raiders and sulphurhounds (BS shows them as 3 and 4). In the Admech codex on pages 92-93 both of the rangers and vanguards powers are 2. In the Admech codex on pages 100-101 both the raiders (power 2) and sulphurhounds (power 3).

**Device and data (please complete the following information):**
 windows 10 and iphone versions
 BattleScribe v2.03.21.166

**Comment by AbonShell** [comment] 2022-04-14 00:09
Duplicate of #11129

**Closed as completed by AbonShell** 2022-04-14 00:09 UTC

**Comment by williamcaw** [comment] 2022-04-14 00:45
other reasons why this was closed is that there was a update. this happens from time to time and it happened on February 2 2022. and updated march 16 2022

**Comment by AbonShell** [comment] 2022-04-14 00:56
Power level ratings was the most recently updated thing that touched them
