### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#306] opened 2017-06-20 19:05 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.03

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** App incorrectly says I have to many lasgun selections for veterans in a command squad if you have more than 1 vet with a lasgun but will correctly allow just 1 vet

**Comment by alphalas** [comment] 2017-06-20 19:19
duplicate of #290

**Closed as completed by alphalas** 2017-06-20 19:19 UTC
Labels: ✔ Res: duplicate, 💾 Cat: Imperium - Astra Militarum, Area: validation
