### ISSUE TITLE
Imperium Astra Militarum: Tempestus Scions: error on max special weapons

### ISSUE THREAD

**Issue by Viper666-Qc** [BSData/wh40k-9e#91] opened 2017-06-16 23:06 UTC
**File/Catalogue:** Imperium Astra Militarum
**BattleScribe version:** 2.01.
**Platform:** Windows
**Dropbox:** Yes
**Description:** Tempestus Scions: I get an error when choosing 2 special weapons (...has 1 too many selection from special weapons max 1).  They can have 2.

**Comment by alphalas** [comment] 2017-06-16 23:08
duplicate of #6

**Closed as completed by alphalas** 2017-06-16 23:08 UTC
Labels: ✔ Res: duplicate, 💾 Cat: Imperium - Astra Militarum, Area: validation
