### ISSUE TITLE
[Anon] Bug report: Aeldari - Harlequins.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11805] opened 2022-08-28 21:51 UTC
**File:** Aeldari - Harlequins.catz

**BattleScribe version:** 3.25.38

**Platform:** Android

**Dropbox:** No

**Description:** BattleScribe v2.03.25.338
Ever since the newest implementation of Relic/Warlord Trait strategems for Harlequins characters, the Treasure of Aeldari strategem does not unlock the option for other characters to choose a relic. The only way to actually get a relic, is to click the "Relic" strategem, even though that strategem is only able to be used once. Thanks in advance.

**Comment by Mad-Spy** [comment] 2022-08-28 22:08
Duplicate of #11778

**Closed as completed by Mad-Spy** 2022-08-28 22:08 UTC
