### ISSUE TITLE
Astra Militarum units start out empty

### ISSUE THREAD

**Issue by GuillermoDiazGarcia** [BSData/wh40k-9e#9101] opened 2020-12-27 11:17 UTC
**File/Catalogue:** Astra Militarum

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:**
The following units start out empty, even though they didn't do that before:
Lord commissar
Company commander
Infantry squad (starts with only the sergeant, but the sergeant has no weapons either)
Astropath
Bullgryns
Command squad
Commissar
Platoon commander
Veterans (same issues as infantry squad)
Manticore (comes without hull weapon)

**Comment by Technoblazed** [comment] 2020-12-27 11:23
Dupe of https://github.com/BSData/wh40k/issues/9095

**Closed as completed by Technoblazed** 2020-12-27 11:23 UTC
