### ISSUE TITLE
[Anon] Bug report: Imperium - Dark Angels.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8440] opened 2020-10-29 20:56 UTC
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Lazarus is included in the app at 160 points, but I believe he is 110 under the October 5, 2020 errata. Apologies if I have missed a subsequent update and thank you for everything you do!

**Comment by Technoblazed** [comment] 2020-10-29 20:56
Dupe of https://github.com/BSData/wh40k/issues/8417. Fixed in master.

**Closed as completed by Technoblazed** 2020-10-29 20:56 UTC
Labels: ✔ Res: deprecated
