### ISSUE TITLE
[Anon] Bug report: Imperium - Adepta Sororitas.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7653] opened 2020-07-29 04:23 UTC
**File:** Imperium - Adepta Sororitas.catz

**BattleScribe version:** 9.00.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Sororitas Storm Bolters are listed as 4pts each, should be 3 each.

**Comment by williamcaw** [comment] 2020-07-29 05:17
dupe of #7434 it is fixed

**Closed as completed** 2020-07-29 08:02 UTC
