### ISSUE TITLE
Imperium - Space Wolves - Skyclaw Squad Size Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#537] opened 2017-06-28 18:02 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** Skyclaw - unit contains 4 basic model + serg, i want give 2 models special weapon (becoming 7 models in unit), but basic models selector minimum 4 instead of 2 ( 5 models in unit)

**Comment by FarseerVeraenthis** [comment] 2017-06-30 10:10
Duplicate of #437

**Closed as completed by FarseerVeraenthis** 2017-06-30 10:10 UTC
Labels: ✔ Res: duplicate, Area: selections, 💾 Cat: Imperium - Space Wolves
