### ISSUE TITLE
Chaos - Death Guard - Plague Champion should have access to combi-weapons

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#579] opened 2017-06-30 19:22 UTC
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** Plague Marines Plague Champion should have access to combi-type weapons when replacing bolt pistol and boltgun (according to champion equipment he might select 2 normal weapons, or 1 combi-type)

**Comment by cartag** [comment] 2017-07-01 00:43
Duplicate of #533

**Closed as completed by cartag** 2017-07-01 00:43 UTC
Labels: ✔ Res: duplicate, Area: selections, 💾 Cat: Chaos - Death Guard
