### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8121] opened 2020-09-16 12:30 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Ynnari warlord trait. When you select ynnari warlord you cannot actually select a trait.

**Comment by Mad-Spy** [comment] 2020-09-16 12:56
Duplicate of #8122

**Closed as completed by Mad-Spy** 2020-09-16 12:56 UTC
