### ISSUE TITLE
Blood Angels: Librarian Dreadnought has no access to WLT Strat under Arks of Omen game type

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12297] opened 2023-01-18 16:23 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** I cannot add any warlord traits to my Librarian Dreadnought. I can check them box for both the 'Warlord' and 'Angel Exemplar' but no traits pop up to be able to select from.

**Comment by Mad-Spy** [comment] 2023-01-28 19:51
Duplicate of #12242

**Closed as completed by Mad-Spy** 2023-01-28 19:51 UTC
Labels: Area: selections, 💾 Cat: Imperium - Blood Angels, Type: bug
