### ISSUE TITLE
[Anon] Bug report: Imperium - Adepta Sororitas.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12391] opened 2023-01-27 21:39 UTC
**File:** Imperium - Adepta Sororitas.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Morvenn Vahl cannot take a warlord trait, even if she's the warlord.

**Comment by Mad-Spy** [comment] 2023-01-27 22:24
Duplicate of #12295

**Closed as completed by Mad-Spy** 2023-01-27 22:24 UTC
