### ISSUE TITLE
[Anon] Bug report: Chaos - Death Guard.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9308] opened 2021-01-25 10:00 UTC
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.03.21

**Platform:** Android

**Dropbox:** No

**Description:** Bubonic axe for death guard terminators should be +2 strength, not +1.

**Comment by GenWilhelm** [comment] 2021-01-25 10:06
Duplicate of #9300

**Closed as completed by GenWilhelm** 2021-01-25 10:06 UTC
Labels: ✔ Res: duplicate, Area: text/rule/profile, 💾 Cat: Chaos - Death Guard
