### ISSUE TITLE
[Anon] Bug report: Chaos - Thousand Sons.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8821] opened 2020-11-18 03:31 UTC
**File:** Chaos - Thousand Sons.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** In existing and new forces the Vindicator is no longer listed for Thousand Sons under heavy support.

**Comment by Valorcalls** [comment] 2020-11-18 03:32
Duplicate of #8820

**Closed as completed by Valorcalls** 2020-11-18 03:32 UTC
