### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12077] opened 2023-01-05 19:36 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Dark apostle (unit) does not list Dark Apostle, only 2x dark disciples. 
Cannot generate dark apostle character for yellow scribe (bstts), as model is not included

**Comment by AbonShell** [comment] 2023-01-05 19:40
Duplicate of #12012

**Closed as completed by AbonShell** 2023-01-05 19:40 UTC
