### ISSUE TITLE
XV9 missing support systems

### ISSUE THREAD

**Issue by SSSlippy** [BSData/wh40k-9e#488] opened 2017-06-26 22:16 UTC
**File/Catalogue:** 

**BattleScribe version:** 2.01.02

**Platform:** Windows
**Dropbox:** No

**Description:** XV9 suit is suppose to have one support system.

**Comment by amis92** [comment] 2017-06-27 00:50
Fixed already, also duplicate of #470

**Closed as completed by amis92** 2017-06-27 00:50 UTC
Labels: ✔ Res: duplicate, Area: selections, ✔ Res: deprecated, 💾 Cat: T'au Empire
