### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7631] opened 2020-07-28 19:36 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** "Adeptus sororitas Storm bolter" on warhammer 40k is wrong points.
You have "4 point" on it.

Its actually 3 point

**Comment by williamcaw** [comment] 2020-07-28 20:55
dupe of #7434 it is fixed

**Closed as completed** 2020-07-29 07:59 UTC
