### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#219] opened 2017-06-19 06:44 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** It's currently not possible to include Adeptus Mechanicus and Astra Telepathica units with the Astra Militarum keyword in Astra Militarum detachments.

**Comment by raptor1770** [comment] 2017-06-19 15:35
I believe this issue is explained by #77

**Comment by alphalas** [comment] 2017-06-19 20:53
duplicate of #207

**Closed as completed by alphalas** 2017-06-19 20:53 UTC
Labels: ✔ Res: duplicate, ✔ Res: by design
