### ISSUE TITLE
Astra Militarum Commissars do not have voice of command

### ISSUE THREAD

**Issue by sounderdisc** [BSData/wh40k-9e#7348] opened 2020-07-19 22:19 UTC
**File/Catalogue:**  Astra Militarum

**BattleScribe version:** 2.03.21

**Platform:** Windows & Android

**Dropbox:** No

**Description:** Astra Militarum Commissars do not have voice of command, but they do on battlescribe. There is also an FAQ for the summary execution ability that reads " The first time an Astra
Militarum unit fails a Morale test during the Morale
phase whilst it is within 6" of any friendly Commissars,
you can execute a model. If you do, one model of your
choice in that unit is slain and the Morale test is rerolled (do not include this slain model when re-rolling
the Morale test).’"

**Comment by alphalas** [comment] 2020-07-21 05:17
duplicate of #7251 ((and like 6 other reports...

https://github.com/BattleScribe/Release/issues/218

**Closed as completed** 2020-07-21 05:18 UTC
