### ISSUE TITLE
[Anon] Bug report: Chaos - Daemons.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10978] opened 2022-02-13 10:04 UTC
**File:** Chaos - Daemons.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The seeker leader 'Heartseeker' is still listed as 18 points, when the unit has been correctly dropped to 16 points.

**Comment by Mad-Spy** [comment] 2022-02-13 10:20
Duplicate of #10971

**Closed as completed by Mad-Spy** 2022-02-13 10:20 UTC
