### ISSUE TITLE
Space Marines FW - Sicaran Arcus is overpriced

### ISSUE THREAD

**Issue by kdotalpha** [BSData/wh40k-9e#9557] opened 2021-03-06 08:27 UTC
File/Catalogue: Imperium - Space Marines v234

BattleScribe version: 2.03.

Platform: Windows

Dropbox: Don't know what this means

Description: The Sicaran Arcus costs 155pts including the Arcus launcher and a Heavy Bolter. Battlescribe charges for the first Heavy Bolter making the tank cost 170pts, which is 15 over. This was prematurely closed earlier without looking into the issue, so re-posting with pics attached.

![IMG-2550](https://user-images.githubusercontent.com/7718531/110200378-7c02c700-7e12-11eb-92a6-f9aafe1ca2a6.jpg)
![IMG-2549](https://user-images.githubusercontent.com/7718531/110200379-7d33f400-7e12-11eb-90e0-8b7c67b6d138.jpg)

**Comment by Mad-Spy** [comment] 2021-03-06 08:44
Duplicate of #9556

**Closed as completed** 2021-03-06 08:44 UTC
