### ISSUE TITLE
[Anon] Bug report: Chaos - Thousand Sons.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7725] opened 2020-07-30 21:51 UTC
**File:** Chaos - Thousand Sons.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Lord of war or HQ selections are not listed on the supreme command detachment.

**Comment by williamcaw** [comment] 2020-07-30 22:20
dupe of #7666

**Closed as completed** 2020-07-30 22:24 UTC
Labels: ✔ Res: duplicate
