### ISSUE TITLE
Arkurian Shadowsword

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-9e#7913] opened 2020-08-11 10:07 UTC
![gw-99590105329-0](https://user-images.githubusercontent.com/45168674/89885275-b846af80-dbc2-11ea-8544-f9132f8ccbcd.jpg)

Arkurian Shadowsword doesn't have any hull heavy bolters. You need to change the file to take this into account.

**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Mad-Spy** [comment] 2020-08-11 10:07
Duplicate of #7906

**Closed as completed by Mad-Spy** 2020-08-11 10:07 UTC
