### ISSUE TITLE
[Anon] Bug report: Tyranids.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10933] opened 2022-02-05 18:05 UTC
**File:** Tyranids.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Since the last update the point cost of all reaver weapon udates was changed to 0. I assume that was unintentionally. Keep up the great work and thanks for all your effort.

**Comment by SoSaltySalt** [comment] 2022-02-06 07:49
Pretty sure their gear was changed to not cost anything in the latest MFM

**Comment by GenWilhelm** [comment] 2022-02-06 13:28
Duplicate of #10878

**Closed as completed by GenWilhelm** 2022-02-06 13:28 UTC
Labels: ✔ Res: duplicate, 💾 Cat: Tyranids
