### ISSUE TITLE
[Anon] Bug report: Imperium - Adepta Sororitas.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7458] opened 2020-07-27 07:37 UTC
**File:** Imperium - Adepta Sororitas.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** stormbolter price incorrect for dominions and battle sisters
expected 3
actual 4

**Comment by williamcaw** [comment] 2020-07-27 07:39
dupe of #7439

**Comment by williamcaw** [comment] 2020-07-27 07:40
its being worked on dupe #7434

**Closed as completed** 2020-07-27 13:20 UTC
