### ISSUE TITLE
New feature - Crusade added to Game Type

### ISSUE THREAD

**Issue by daemonell** [BSData/wh40k-9e#8185] opened 2020-09-20 11:14 UTC
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

Not sure if you are already working on Crusade game type, mark this duplicate if so.

**Comment by Technoblazed** [comment] 2020-09-20 11:53
Duplicate of https://github.com/BSData/wh40k/issues/8068.

TLDR; It'd add too much strain on devices with smaller memory capacities, so won't be added.

**Closed as completed by Technoblazed** 2020-09-20 11:53 UTC
Labels: ✔ Res: wontfix
