### ISSUE TITLE
[Anon] Bug report: Imperium - Deathwatch.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8824] opened 2020-11-18 15:49 UTC
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** Deathwatch Vanguard Veterans can take Heavy Thunder Hammer for free, it should cost 15pts.

**Comment by Technoblazed** [comment] 2020-11-18 16:58
Dupe of https://github.com/BSData/wh40k/issues/8753

**Closed as completed by Technoblazed** 2020-11-18 16:58 UTC
