### ISSUE TITLE
[Anon] Bug report: Aeldari - Craftworlds.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8061] opened 2020-08-31 06:03 UTC
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** PL for Dark Reapers if not correct. 5 reapers should be 9 PL instead of 14.

**Comment by DrTobogganMD** [comment] 2020-08-31 13:41
Duplicate of #8056

**Closed as completed by DrTobogganMD** 2020-08-31 13:41 UTC
Labels: Area: costs, ✔ Res: duplicate, 💾 Cat: Aeldari - Drukhari, Type: bug
