### ISSUE TITLE
Adeptus Astartes Rites of War warlord trait description is missing text

### ISSUE THREAD

**Issue by rjr213** [BSData/wh40k-9e#8533] opened 2020-10-30 16:17 UTC
**File/Catalogue:** Iron Hands v.26

**BattleScribe version:** 2.03.

**Platform:** iOS

**Dropbox:** No

**Description:** Detailed issue description.

Description is missing text see below 
![C317AB4C-60F6-43C5-AC50-73DE88A9B01E](https://user-images.githubusercontent.com/8421197/97730128-d88f5780-1aa9-11eb-9716-74e5575a2b0c.jpeg)

![0598B5FE-BEFA-4AB9-8F28-BFA3E22BEF06](https://user-images.githubusercontent.com/8421197/97730131-d9c08480-1aa9-11eb-86dc-988d4f90fd9e.jpeg)

**Comment by ThePants999** [comment] 2020-10-31 00:13
Duplicate of #8432

**Closed as completed** 2020-11-01 04:27 UTC
Labels: Area: text/rule/profile, Type: bug, 💾 Lib: Imperium - Space Marines
