### ISSUE TITLE
Deathwatch - Land Raider Redeemer Sponsons

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k-9e#531] opened 2017-06-28 15:40 UTC
**File/Catalogue:** Imperium - Deathwatch

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** Yes

**Description:** Land Raider Redeemer should have Flamestorm Cannons, instead of Twin Lascannons.

**Comment by FarseerVeraenthis** [comment] 2017-06-28 18:29
Duplicate of #477

**Closed as completed by FarseerVeraenthis** 2017-06-28 18:29 UTC
Labels: ✔ Res: duplicate, Area: selections, 💾 Cat: Imperium - Deathwatch
