### ISSUE TITLE
[Anon] Bug report: Chaos - Death Guard.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8491] opened 2020-10-30 06:32 UTC
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Multi melta and missile launcher point values for vehicles are wrong. Currently, your days days Death Guard Myphitic Blight Haulers are 90 points per model when they should be 100.

**Comment by Technoblazed** [comment] 2020-10-30 06:55
Duplicate of https://github.com/BSData/wh40k/issues/8454.

**Closed as completed by Technoblazed** 2020-10-30 06:55 UTC
Labels: ✔ Res: duplicate
