### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9348] opened 2021-01-30 13:08 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.21

**Platform:** Mac

**Dropbox:** No

**Description:** Space wolves missing units from Space Marine Codex

Examples include Apothecary, Primaris Apothecary, Vanguard Veteran squad. 

Apologies if this is a duplicate.

**Comment by Valorcalls** [comment] 2021-01-30 13:08
Duplicate of #9347

**Closed as completed by Valorcalls** 2021-01-30 13:08 UTC
