### ISSUE TITLE
Tyranids - Genestealer Cults: Neophyte Hybrid leader should have option for shotgun

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10906] opened 2022-02-03 16:58 UTC
**File:** Tyranids - Genestealer Cults.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Neophyte Hybrids

Neophyte hybrid leader should have option for shotgun

**Comment by GenWilhelm** [comment] 2022-02-04 11:54
Duplicate of #10879

**Closed as completed by GenWilhelm** 2022-02-04 11:54 UTC
Labels: ✔ Res: duplicate, Area: selections, 💾 Cat: Tyranids - Genestealer Cults, Type: bug
