### ISSUE TITLE
Blood Angels - Inferno Pistol and Flamer Pistol wargear missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7492] opened 2020-07-27 12:26 UTC
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Blood angels wargear isn't fully updated, as it lacks the inferno pistol and flamer pistol options that are supposed to be available to the units that can take them.

**Comment by Dunamis55** [comment] 2020-07-27 17:29
Duplicate of #7521

**Closed as completed by Dunamis55** 2020-07-27 17:29 UTC
