### ISSUE TITLE
Tyranids - Genestealer Cults: Achilles Ridgerunner points not updated

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10897] opened 2022-02-03 00:51 UTC
**File:** Tyranids - Genestealer Cults.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Hello. Achilles ridgerunners should be 80 points instead of 70 points. Thanks

**Comment by GenWilhelm** [comment] 2022-02-03 10:10
Duplicate of #10881

**Closed as completed by GenWilhelm** 2022-02-03 10:10 UTC
Labels: Area: costs, ✔ Res: duplicate, 💾 Cat: Tyranids - Genestealer Cults, Type: bug
