### ISSUE TITLE
Drukhari Raider doesn't allow Coven subfaction

### ISSUE THREAD

**Issue by FranklinTemba** [BSData/wh40k-9e#9681] opened 2021-04-06 09:37 UTC
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

**Description:** Raiders only allow for selecting Kabal or Wych Cult as the subfaction. Codex also permits Raiders to be a Haemonculus Coven unit.

**Comment by Valorcalls** [comment] 2021-04-06 09:38
duplicate of #9680 and also should be fixed for next release

**Closed as completed by Valorcalls** 2021-04-06 09:38 UTC
