### ISSUE TITLE
Astra Militarum - Bullgryn bone 'ead should be 30 pts not 35 pts

### ISSUE THREAD

**Issue by Andrew1178** [BSData/wh40k-9e#11504] opened 2022-06-29 14:27 UTC
Describe the bug
Astra Militarum doesn't have the Nephilim points update taken into account for Bullgryn bone 'eads. They should be 30 points, not 35.

To Reproduce
Compare unit point to the [Munitorum Field Manual 2022 MkII]
](https://www.warhammer-community.com/wp-content/uploads/2022/06/mYZ4b5gZUiktj4GI.pdf)

Expected behavior
The points in Battlescribe should match the points update in the field manual. (35 -> 30)

Screenshots
N/A

Device and data (please complete the following information):

    OS: Android, Windows
    BattleScribe version 2.03.25
    Release version v9.4.1

Additional context
N/A

**Comment by Mad-Spy** [comment] 2022-06-29 14:29
Duplicate of #11481

**Closed as completed by Mad-Spy** 2022-06-29 14:29 UTC
