### ISSUE TITLE
[Anon] Bug report: Imperium - Blood Angels.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8505] opened 2020-10-30 09:56 UTC
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 9.01.00

**Platform:** Android

**Dropbox:** No

**Description:** The datasheets for the primaris outrider atv is missing from the update

**Comment by Dunamis55** [comment] 2020-10-30 12:26
Duplicate of #8483

**Closed as completed by Dunamis55** 2020-10-30 12:26 UTC
