### ISSUE TITLE
[Anon] Bug report: Aeldari - Drukhari.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9709] opened 2021-04-10 11:08 UTC
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Lelith Hesperax does not have the Master Succubus keyword when she should. This also stops you from adding a Hekatrix Bloodbrides troop to the detachment.

**Comment by Valorcalls** [comment] 2021-04-10 11:14
Duplicate of #9694

**Closed as completed by Valorcalls** 2021-04-10 11:14 UTC
