### ISSUE TITLE
[Anon] Bug report: Imperium - Blood Angels.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11617] opened 2022-07-09 08:21 UTC
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Astorath and other named Characters have still no access to their  destined Warlordtraits when choosing them as Warlord.

**Comment by AbonShell** [comment] 2022-07-09 08:22
Duplicate of #11615

**Closed as completed by AbonShell** 2022-07-09 08:22 UTC
