### ISSUE TITLE
[Anon] Bug report: Tyranids - Genestealer Cults.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12604] opened 2023-03-17 14:09 UTC
**File:** Tyranids - Genestealer Cults.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Genestealer Cults boarding patrol will only allow you to include 1 character (HQ or Elite)

Rules wise they can include upto 3 characters, but only 1 can have 5+ wounds

**Comment by Mad-Spy** [comment] 2023-03-17 20:11
Duplicate of #12194

**Closed as completed by Mad-Spy** 2023-03-17 20:11 UTC
