### ISSUE TITLE
[Anon] Bug report: Imperium - Blood Angels.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12316] opened 2023-01-20 17:31 UTC
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 9.07.01

**Platform:** Windows

**Dropbox:** Yes

**Description:** Warlord Trait options for the Librarian Dreadnought don't appear when selected to be the Warlord or the Angel Exemplar. They do show up if he's selected to be the Hero of the Chapter.

**Comment by Mad-Spy** [comment] 2023-01-21 03:41
Duplicate of #12242

**Closed as completed by Mad-Spy** 2023-01-21 03:41 UTC
