### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12335] opened 2023-01-22 11:13 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Space Wolves Elites. Wolfguard Terminator - Thunder Hammer Must be no Cost instaed of 9 pts

**Comment by Mad-Spy** [comment] 2023-01-22 11:42
Duplicate of #12186

**Comment by Mad-Spy** [comment] 2023-01-22 11:42
Duplicate of #12334

**Closed as completed by Mad-Spy** 2023-01-22 11:42 UTC
