### ISSUE TITLE
[Anon] Bug report: Chaos - Death Guard.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10979] opened 2022-02-13 14:07 UTC
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Plague Burst Crawler is 9 power level but should be 8. Thanks! Keep up the amazing work

**Comment by Mad-Spy** [comment] 2022-02-13 14:08
Duplicate of #10953

**Closed as completed by Mad-Spy** 2022-02-13 14:08 UTC

**Comment by Mad-Spy** [comment] 2022-02-13 14:09
This is fixed in the current release. Update your data.
