### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7585] opened 2020-07-28 06:29 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Problem: The strategem Plaguechosen (Death Guard- War of the spider). According to the text on the strat you can give a warlod trate to a death gurad character after selecting your warlod (se full text on the strat bellow). Now when you select a warlod in a non death guard detachment and try to use this strat on a character in the deathguard detachment you get a roster validation error that you cant use the strat. As far as i can se there is nothing in the text on the strat (or in the FAQ as of yesterday), that says the warlord must be in a death gurad detachment for you to use this strat (but ofc the character that you are using the strategem on must be). Nor is this a requierment for other similar strats in other factions. 

The strategem states:
Use this Stratagem before the battle, after nominating your Warlord. Select one DEATH GUARD CHARACTER model from your army that does not have a Warlord Trait and determine one Warlord Trait for it; it is regarded as your Warlord for the purposes of that Warlord Trait. Each Warlord Trait in your army must be unique (if randomly generated, re-roll duplicate results).

Fix: Remove the validation error as long as ypu have selected a warlord (in any detachmnet) before using the strategem. 

Ps. Great jobb getting all the data out so fast after release! Thanks for that.

**Comment by Mad-Spy** [comment] 2020-07-28 08:30
duplicate of #7424

**Closed as completed by Mad-Spy** 2020-07-28 08:30 UTC
