### ISSUE TITLE
Astra Militarum Scout Sentinel 

### ISSUE THREAD

**Issue by Deecee29** [BSData/wh40k-9e#7972] opened 2020-08-16 12:22 UTC
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** When you add Scout Sentinel to an army it has the first costing 6 power level and every following costs 3, so a full three man unit cost 12 power level when it should only cost 9

**Comment by Mad-Spy** [comment] 2020-08-16 18:50
Duplicate of #7955

**Closed as completed by Mad-Spy** 2020-08-16 18:50 UTC
