### ISSUE TITLE
Imperium - Astra Militarum: Unable to give Scions the correct number of special weapons

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#46] opened 2017-06-16 16:20 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** No

**Description:** Scions now have the option for two specials for every five models. This option is not reflected in the data files. It can be worked around creatively but will be listed as an invalid list.

**Comment by alphalas** [comment] 2017-06-16 20:31
Duplicate of #6

**Closed as completed by alphalas** 2017-06-16 20:31 UTC
Labels: ✔ Res: duplicate, 💾 Cat: Imperium - Astra Militarum, Area: validation
