### ISSUE TITLE
[Anon] Bug report: Aeldari - Drukhari.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9686] opened 2021-04-06 14:11 UTC
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When trying to add Lelith Hesparax, I cannot seem to add her regardless of what Cult of Strife obsession I select. There might be an error with her faction locking or something where cult of strife isn’t actually making her become available or something, I’m not sure, but I’ve tried updating data like 5 times and tried every cult obsession just to make sure I’m not doing something wrong.

**Comment by Valorcalls** [comment] 2021-04-06 15:47
Duplicate of #9677

**Closed as completed by Valorcalls** 2021-04-06 15:47 UTC
