### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#280] opened 2017-06-20 05:01 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** No

**Description:** Tempestor scions 
Tempestor - plasma pistol cost 5 (currently - 7) and currently printing as "hot-shot laspistol: plasma pistol"
Scions - frak&krak granade adding as additinal scions (dont need because they all have granades for free), basic scions have hot-shot lasgun, witch cost 1 (scion with hot-shot lasgun cost 10), currently adding only scions for 9 pts

**Comment by alphalas** [comment] 2017-06-20 11:05
Duplicate of #231

**Closed as completed by alphalas** 2017-06-20 11:05 UTC
Labels: Area: costs, ✔ Res: duplicate, 💾 Cat: Imperium - Astra Militarum
