### ISSUE TITLE
Astra Militarum Errors

### ISSUE THREAD

**Issue by Eerieuk** [BSData/wh40k-9e#189] opened 2017-06-18 17:16 UTC
**File/Catalogue:Astra Militatum** 

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** Incorrect data

**Armoured sentinal** - Explodes rule incorrect.  It is not the same as the general explodes.  It should be units within 3" take 1 mortal wound.
**Commissar** - Points incorrect currently listed as 25 base they actually 30pts
**Special weapons** - sniper rifle cost 2 pts not 4.
**Knight commander pask**. listed as a command battle tank as default option but the points for the battle cannon are listed as no cost. A battle cannon cost 22pts so  Pask Battle Tank is 177pts + HB 8pts + battle cannon 22pts -207 pts base.  (also when  click on Command battle tank under pasks listing it allows u to added the battle cannon points in but there listed as 30 pts, should be 22 pt)
**Lord Castellan Creed** - His points cost is supposed to be 70pts including wargear. hes currently listed as 80points.
**Nork Deddog** - His points cost is supposed to be 80pts including wargear. hes currently listed as 85points
**Militarium tempestus command squad** - scions are armed with hotshot volley gun. they should be armed with hot shot lasguns by default. Hot-shot volley should be an selectable upgrade.
**Veterans** are missing the option to take a Heavy Flamer
**Valkyrie** - hull weapon - lascannon listed at 25 pts should be 20 points
**Tuarox prime** - hull mounted  two autocannons should cost 30 points - two hot-shot volley guns should cost 18pts
**Vechiles** - Stat Damage entries missing

**Comment by ExLibrisMortis** [comment] 2017-06-18 17:20
Also for Valkyries, there's no option to add Heavy Bolters on them

**Comment by AbsoluteManiac** [comment] 2017-06-18 23:30
Additionally, special weapon scions are armed with a hot shot volley gun that cannot be unequipped

**Comment by alphalas** [comment] 2017-06-19 21:33
Duplicate of #231

**Closed as completed by alphalas** 2017-06-19 21:33 UTC
Labels: Area: costs, ✔ Res: duplicate, Area: selections, Area: text/rule/profile, 💾 Cat: Imperium - Astra Militarum
