### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7460] opened 2020-07-27 08:17 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Thunder Hammer Points: for characters is 40pts, now it cost 15pts for everybody

**Comment by DessaiImrane** [comment] 2020-07-27 08:49
I can't reproduce this one : i've tested on Wolf Lord and Wolf Guard Battle Leader.

In the CAT file, it is correct : 

![image](https://user-images.githubusercontent.com/1715606/88522571-99afb880-d007-11ea-87fd-1e2148194ba7.png)

**Comment by Gingrel** [comment] 2020-07-27 12:19
To clarify for OP. 40 points for characters is correct behaviour as per the 9e MFM. Not sure if that's what you meant or not.

**Comment by DessaiImrane** [comment] 2020-07-27 13:28
Agree.

So I guess you can close this one.

What i've tested is : wether Character has TH for 40 pts. It is the case in 9e MFM and in the app.

So no problem there.

**Closed as completed** 2020-07-27 13:28 UTC
