### ISSUE TITLE
[Anon] Bug report: Aeldari - Drukhari.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9689] opened 2021-04-06 22:36 UTC
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** I cannot add the HQ - Lelith Hesperax to my army. Tried choosing both versions of Cult of Strife to make her appear as an option but she's nowhere to be seen.

**Comment by WindstormSCR** [comment] 2021-04-06 22:49
duplicate of #9677

**Closed as completed by WindstormSCR** 2021-04-06 22:49 UTC
