### ISSUE TITLE
[Anon] Bug report: Imperium - Iron Hands.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9226] opened 2021-01-12 08:22 UTC
**File:** Imperium - Iron Hands.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Teeth of Mars Special issue Wargear is missing from menu for all iron hands characters.

**Comment by Valorcalls** [comment] 2021-01-12 08:27
Duplicate of #9219

**Closed as completed by Valorcalls** 2021-01-12 08:27 UTC
