### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11378] opened 2022-06-09 02:40 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Hi. Great work! I don’t see an option to use the Vanguard Spearhead in Spacewolf and Successor lists. Seems applicable to any chapter per Vigilus Alone Supplement. Please add if you can. Your work continues to be way better than the GW App. Thanks for all you Do!

**Comment by Mad-Spy** [comment] 2022-06-10 07:45
Duplicate of #11208

**Closed as completed by Mad-Spy** 2022-06-10 07:45 UTC
