### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#283] opened 2017-06-20 08:16 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** No

**Description:** Sniper Rifles are listed as 4 points per model throughout the army, when they should be 2 points per model.

**Comment by alphalas** [comment] 2017-06-20 11:06
Duplicate of #231

**Closed as completed by alphalas** 2017-06-20 11:06 UTC
Labels: Area: costs, ✔ Res: duplicate, 💾 Cat: Imperium - Astra Militarum
