### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8509] opened 2020-10-30 11:25 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** When adding units to the faction 'Imperium - Adeptus Astartes - Blood Angels v198' there is no option to add Invader ATV under Fast Attack. This option exists when using other chapters such as Salamanders.

Please note this also effects the Android application version as well.

**Comment by Dunamis55** [comment] 2020-10-30 12:27
Duplicate of #8483

**Closed as completed by Dunamis55** 2020-10-30 12:27 UTC
