### ISSUE TITLE
Imperium - Dark Angels: Something about Ravenwing and Deathwing WLTs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9554] opened 2021-03-05 21:47 UTC
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.33

**Platform:** Android

**Dropbox:** No

**Description:** 
1. Deathwing knights and Deathwing Command Squad missing the CORE keyword. Already fixed in #9546

2. Ravenwing and Deathwing warlord traits should be selectable like other warlord traits when criteria are met, instead of being radial one-or-the-other due to the wording of Paragon of the Chapter

**Comment by Technoblazed** [comment] 2021-03-06 09:26
Duplicate of https://github.com/BSData/wh40k/issues/9546 for the first part of the issue.

**Closed as completed** 2021-03-10 09:25 UTC
Labels: 💾 Cat: Imperium - Dark Angels, Area: validation, Type: bug
