### ISSUE TITLE
[Anon] Bug report: Chaos - Death Guard.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10893] opened 2022-02-02 15:59 UTC
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Deathshroud Champion: Second Plaguespurt Gauntlet had it's cost removed in the MFM, is still being listed as 5 points.

**Comment by Mad-Spy** [comment] 2022-02-02 16:03
Duplicate of #10883

**Comment by uberjew666** [comment] 2022-02-02 16:04
You beat me to it by 1 minute.

**Closed as completed by Mad-Spy** 2022-02-02 16:03 UTC
