### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12412] opened 2023-01-30 20:43 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Chaos Possessed Chaos Icon cost is 0pts, should be 5pts. Thanks!

**Comment by Mad-Spy** [comment] 2023-01-30 20:58
Duplicate of #12403

**Closed as completed by Mad-Spy** 2023-01-30 20:58 UTC
