### ISSUE TITLE
Black Templars Have Scout Squads as Troop Choices 

### ISSUE THREAD

**Issue by VileCalumnies** [BSData/wh40k-9e#8527] opened 2020-10-30 14:55 UTC
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

**Description:** Scout Squads are listed under Troops for Black Templars, should be Elites.

**Comment by Mad-Spy** [comment] 2020-10-30 16:06
Duplicate of #8443

**Closed as completed by Mad-Spy** 2020-10-30 16:06 UTC
Labels: Area: selections, Type: bug, 💾 Cat: Imperium - Black Templars
