### ISSUE TITLE
[Anon] Bug report: Chaos - Thousand Sons.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11360] opened 2022-06-05 04:25 UTC
**File:** Chaos - Thousand Sons.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Scarab Occult Terminators do not count for the Bray tag. Meaning if my list has one Tzaangor unit and one Terminator unit I still receive the Roster Error.

**Comment by AbonShell** [comment] 2022-06-05 06:09
Duplicate of #11348

**Closed as completed by AbonShell** 2022-06-05 06:09 UTC
