### ISSUE TITLE
Baal Predator Error

### ISSUE THREAD

**Issue by BalancedHydra** [BSData/wh40k-9e#8806] opened 2020-11-16 03:21 UTC
**File/Catalogue:** 

**BattleScribe version:** 2.03.21

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** 
The costs for the heavy flamer sponsons should be 30 instead of 45 (15 per flamer)

**Comment by Mad-Spy** [comment] 2020-11-16 09:57
Duplicate of #8765

**Closed as completed by Mad-Spy** 2020-11-16 09:57 UTC
