### ISSUE TITLE
Cannot reach repos

### ISSUE THREAD

**Issue by bubzer** [BSData/wh40k-9e#7825] opened 2020-08-04 15:44 UTC
**File/Catalogue:** Warhammer 40k

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** When I'm trying to add data, it isn't finding any of it. When I'm trying to add it via URL, it's showing this error log

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 34

Details:

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 34
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:180)
	at com.google.gson.Gson.fromJson(Gson.java:755)
	at com.google.gson.Gson.fromJson(Gson.java:721)
	at com.google.gson.Gson.fromJson(Gson.java:670)
	at com.google.gson.Gson.fromJson(Gson.java:642)
	at net.battlescribe.a.c.e.d(BattleScribe:463)
	at net.battlescribe.desktop.common.RepositorySourceWindowController.a(BattleScribe:221)
	at net.battlescribe.desktop.common.RepositorySourceWindowController.access$downloadRepositorySource(BattleScribe:22)
	at net.battlescribe.desktop.common.RepositorySourceWindowController$a.a(BattleScribe:247)
	at net.battlescribe.desktop.common.RepositorySourceWindowController$a.call(BattleScribe:245)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

-------------------- Caused By --------------------

java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 34
	at com.google.gson.stream.JsonReader.expect(JsonReader.java:339)
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:322)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:168)
	at com.google.gson.Gson.fromJson(Gson.java:755)
	at com.google.gson.Gson.fromJson(Gson.java:721)
	at com.google.gson.Gson.fromJson(Gson.java:670)
	at com.google.gson.Gson.fromJson(Gson.java:642)
	at net.battlescribe.a.c.e.d(BattleScribe:463)
	at net.battlescribe.desktop.common.RepositorySourceWindowController.a(BattleScribe:221)
	at net.battlescribe.desktop.common.RepositorySourceWindowController.access$downloadRepositorySource(BattleScribe:22)
	at net.battlescribe.desktop.common.RepositorySourceWindowController$a.a(BattleScribe:247)
	at net.battlescribe.desktop.common.RepositorySourceWindowController$a.call(BattleScribe:245)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by DrTobogganMD** [comment] 2020-08-04 15:45
read the stickies

**Comment by amis92** [comment] 2020-08-04 15:45
Duplicate of #1706

**Closed as completed by DrTobogganMD** 2020-08-04 15:45 UTC
