### ISSUE TITLE
[Anon] Bug report: Tyranids - Genestealer Cults.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8103] opened 2020-09-12 02:00 UTC
**File:** Tyranids - Genestealer Cults.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When using Narrative gametype the Atalan Jackals unit is missing the "Has Battle Honours" option.

**Comment by williamcaw** [comment] 2020-09-12 03:17
dupe of #8102

**Closed as completed** 2020-09-12 04:42 UTC
Labels: ✔ Res: duplicate
