### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11482] opened 2022-06-27 20:35 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Incorrect points.  Bullgryn Bone’ead should be 30 it’s listed as 35.  Infantry Squad sniper rifle should be 0 points it’s listed as 2.  Sorry if this is not the proper way to share this information but I really wanted to get the feedback to the right place!

**Comment by Mad-Spy** [comment] 2022-06-27 21:40
Duplicate of #11481

**Closed as completed by Mad-Spy** 2022-06-27 21:40 UTC
