### ISSUE TITLE
[Anon] Bug report: Aeldari - Craftworlds.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8947] opened 2020-12-02 17:29 UTC
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Hornet weapons are broken and don't show up. They come standard with shiriken cannons and i am unable to change them.

**Comment by Technoblazed** [comment] 2020-12-02 17:30
Dupe of:

https://github.com/BSData/wh40k/issues/8879
https://github.com/BSData/wh40k/issues/8856
https://github.com/BSData/wh40k/issues/8882
https://github.com/BSData/wh40k/issues/8915
https://github.com/BSData/wh40k/issues/8929

-----

RAW the hornet can only take shuriken cannons and cannot replace them as it does not have the required wargear.

**Closed as completed by Technoblazed** 2020-12-02 17:30 UTC
Labels: ✔ Res: duplicate
