### ISSUE TITLE
[Anon] Bug report: Orks - 2021.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10391] opened 2021-08-29 01:27 UTC
**File:** Orks - 2021.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Nobz, Meganobz, and Nob with WAAAGH! Banner no longer have the rule “Keepin’ Order”.

**Comment by AbonShell** [comment] 2021-08-29 01:41
Because that is no longer a rule in the new orks codex. If you wish to have the old ork codex rules, be sure to not use the, Orks - 2021 data.

**Comment by AbonShell** [comment] 2021-08-30 03:26
Misunderstood issue, duplicate of #10399 

Those units still have it in the data, when they should not.

**Closed as completed** 2021-08-30 12:01 UTC
