### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12146] opened 2023-01-14 23:18 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** I updated to 9.7 and the Chaos Forgeworld models are still the incorrect points.

**Comment by Valorcalls** [comment] 2023-01-14 23:53
What chaos forge world models need updated?

**Comment by WindstormSCR** [comment] 2023-01-15 02:21
duplicate of #12159

**Closed as completed by WindstormSCR** 2023-01-15 02:21 UTC
Labels: ⛔ Problem: vague report, Type: bug
