### ISSUE TITLE
[Anon] Bug report: Imperium - Adeptus Mechanicus.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9570] opened 2021-03-09 13:56 UTC
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Adeptus Mechanicus Kastelan Robots Heavy Phosphor blasters due not appear on the list after selecting them in the unit. Combuster and fists appear ok.

**Comment by Technoblazed** [comment] 2021-03-09 13:58
Duplicate of https://github.com/BSData/wh40k/issues/9552. Fixed in next release.

**Closed as completed by Technoblazed** 2021-03-09 13:58 UTC
