### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Knights.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11323] opened 2022-05-29 05:20 UTC
**File:** Chaos - Chaos Knights.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** When taking a dreadblade in an Auxiliary heavy support detachment (added to my csm list), the dreadblade fell bond i choose (both infernal and icono) does not show up in the unit description. The options appear and i can select them when editing the unit,  they just dont show up when i view the unit/list. This does not happen when i am making pure chaos knights lists (using super heavy detachment, not Auxiliary).

**Comment by Mad-Spy** [comment] 2022-05-29 06:32
Duplicate of #11317

**Closed as completed by Mad-Spy** 2022-05-29 06:32 UTC
