### ISSUE TITLE
[Anon] Bug report: Chaos - Death Guard.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7724] opened 2020-07-30 21:48 UTC
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Lord of war or HQ selections are not listed in supreme command detachment.

**Comment by williamcaw** [comment] 2020-07-30 22:19
dupe of #7667

**Closed as completed** 2020-07-30 22:24 UTC
Labels: ✔ Res: duplicate
