### ISSUE TITLE
Imperium - Space Wolves: Grey Hunter and Intercessor costs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7970] opened 2020-08-16 10:41 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Power Level for Grey Hunters is currently 11 (75 points)
Intercessors are 100 points and only 5PL - somethings not right.

**Comment by Technoblazed** [comment] 2020-08-16 20:34
Duplicate of https://github.com/BSData/wh40k/issues/7960.

**Closed as completed by Technoblazed** 2020-08-16 20:34 UTC
Labels: Area: costs, ✔ Res: duplicate, 💾 Cat: Imperium - Space Wolves, Type: bug
