### ISSUE TITLE
[Anon] Bug report: Imperium - Grey Knights.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12492] opened 2023-02-14 02:45 UTC
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Imperium - Grey Knights

Venerable & Regular Dreadnought -> Dreadnought Combat Weapon -> Heavy Flamer is at 10pts. It should be 0pts.

**Comment by Mad-Spy** [comment] 2023-02-14 10:21
Duplicate of #12425

**Closed as completed by Mad-Spy** 2023-02-14 10:21 UTC
