### ISSUE TITLE
Lord of Contagion  Nurgle's Gift ability is from the 8th ed. codex 

### ISSUE THREAD

**Issue by barBUGga** [BSData/wh40k-9e#9415] opened 2021-02-09 11:57 UTC
**File/Catalogue:** Death Guard

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes

**Description:** Now in the v 9.1.14 of 40k file the Lord of Contagion  Nurgle's Gift ability is from the 8th ed. codex (All DEATH GUARD units within 7" of a friendly LORD OF CONTAGION are surrounded by a deadly aura of plague and disease. Roll a dice for each enemy unit that is within 1" of any affected friendly units at the start of your turn; on a 4+ that enemy unit suffers a mortal wound.). in 9th ed codex the nurgle's gift ability is a contagion ability that all units with contagion gains if every unit in your army has the DEATH GUARD keyword and gives enemy units within contagion range -1 Toughness.

**Comment by Mad-Spy** [comment] 2021-02-09 11:59
Duplicate of #9392

**Closed as completed by Mad-Spy** 2021-02-09 11:59 UTC
