### ISSUE TITLE
Add Grukk Facerippa, Goff Rokker and Skrak's Skull-Nobz for Orks open Play. White Dwarf 454

### ISSUE THREAD

**Issue by LestatBCN** [BSData/wh40k-9e#7762] opened 2020-08-01 05:46 UTC
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by fuckingenglish** [comment] 2020-08-01 06:11
Hay it's all ready opened #7437

**Comment by Mad-Spy** [comment] 2020-08-01 06:16
Duplicate of #7437

**Closed as completed by Mad-Spy** 2020-08-01 06:16 UTC
