### ISSUE TITLE
[Anon] Bug report: Imperium - Imperial Knights.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11340] opened 2022-06-01 14:51 UTC
**File:** Imperium - Imperial Knights.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** ~~Súper heavy auxiliary detachment doesn't have forge worlds for questor mechanicus (raven, Taranis, etc)~~(Fixed in next release)
There are no stratagems from warzone charadon book of rust (still valid) that allows admech canticles into imperial knights among other rules
Thx

**Comment by AbonShell** [comment] 2022-06-01 14:54
Otherwise, duplicate of #11253

**Closed as completed by AbonShell** 2022-06-01 14:54 UTC
