### ISSUE TITLE
[Anon] Bug report: Imperium - Adepta Sororitas.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7636] opened 2020-07-28 20:47 UTC
**File:** Imperium - Adepta Sororitas.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** Storm bolters are miss-costed throughout the repository. Currently listed as 4pts, this should be 3pts according to the Munitorum Field Manual.

**Comment by williamcaw** [comment] 2020-07-28 20:56
dupe of #7434 it is fixed

**Closed as completed** 2020-07-29 08:04 UTC
