### ISSUE TITLE
[Anon] Bug report: Chaos - Death Guard.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9330] opened 2021-01-28 02:26 UTC
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 9.01.12

**Platform:** Android

**Dropbox:** Yes

**Description:** Bubonic Axe should be S+2 but it is showing as +1 on blightlord terminators.

**Comment by Valorcalls** [comment] 2021-01-28 02:28
Duplicate of #9300, #9324, #9322, #9308

**Closed as completed by Valorcalls** 2021-01-28 02:28 UTC
