### ISSUE TITLE
[Anon] Bug report: Orks - 2021.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10400] opened 2021-08-30 03:18 UTC
**File:** Orks - 2021.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Problem: In Orks 2021 data, Nobz are incorrectly getting a discount on the second Killsaw when it is selected.  First Saw is 10 points and second is 5 points.  You must select the second for the discount bug to appear.

Solution:  In the 2021 Ork Codex, Killsaws are 10 points each.  There is no discount for a second.

**Comment by AbonShell** [comment] 2021-08-30 03:28
Duplicate of #10392

**Closed as completed** 2021-08-30 12:01 UTC
