### ISSUE TITLE
[Anon] Bug report: Aeldari - Craftworlds.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10508] opened 2021-10-01 16:46 UTC
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 9.02.10

**Platform:** Android

**Dropbox:** No

**Description:** When you have two or more detachments of the same codex i.E. Craftworld you can only give a character in the same detachment an remnant of glory but you should also be able to give an Craftworld Character from another detachment the item.

**Comment by Mad-Spy** [comment] 2021-10-01 17:17
Duplicate of #10494

**Closed as completed by Mad-Spy** 2021-10-01 17:17 UTC
