### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7487] opened 2020-07-27 12:00 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Deathwatch are missing Indomitus units (FAQ gave it to them, but new guns such as the Twin Bolt Rifle do not get SIA yet) 
Deathwatch Intercessors Autobolt Rifles should go from 1pt to 0pt

**Comment by Thairne** [comment] 2020-07-27 13:21
Also duplicate of #7496

**Closed as completed** 2020-07-27 13:22 UTC
