### ISSUE TITLE
Ultramarines Chapter Champion and Ancient can't be given Relics

### ISSUE THREAD

**Issue by CaptainIdaho** [BSData/wh40k-9e#11759] opened 2022-08-09 20:52 UTC
The Ultramarines Chapter Ancient and Chapter Champion unit choices cannot be given Relics despite being characters.

**Comment by Mad-Spy** [comment] 2022-08-09 21:59
Duplicate of #11754

**Closed as completed by Mad-Spy** 2022-08-09 21:59 UTC
Labels: Area: selections, Area: validation, 💾 Cat: Imperium - Ultramarines

**Comment by CaptainIdaho** [comment] 2022-08-17 12:30
This wasn't completed along with the other raised issue. Ultramarines Chapter Champion and Chapter Ancient still do not have access to Relics.
