### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#176] opened 2017-06-18 13:52 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** No

**Description:** In the Tempestus profiles,when selecting a scion with a special weapon, it is automatically populated with a vollygun upgrade and costed appropriately but when a different ranged weapon is selected, the vollygun remains and cannot be removed. The points are still there and it is detected as incorrect for having 1 too many weapon upgrade options. 

Kind regards

**Comment by alphalas** [comment] 2017-06-18 15:44
duplicate of #155

**Closed as completed by alphalas** 2017-06-18 15:44 UTC
Labels: ✔ Res: duplicate, Area: selections, 💾 Cat: Imperium - Adepta Sororitas
