### ISSUE TITLE
Tsons cultists PL error

### ISSUE THREAD

**Issue by darthrevan1234** [BSData/wh40k-9e#10347] opened 2021-08-21 16:59 UTC
**File/Catalogue:** Thousand sons

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
Thousand Sons cultists are currently listed as 3PL rather than the 2PL in the new codex

**Comment by Technoblazed** [comment] 2021-08-21 17:00
Dupe of https://github.com/BSData/wh40k/issues/10343

**Closed as completed by Technoblazed** 2021-08-21 17:00 UTC
