### ISSUE TITLE
Imperium - Astra Militarum: Tempestus Scions weapon validation issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#240] opened 2017-06-19 15:09 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.01

**Platform:** Windows

**Dropbox:** No

**Description:** When choosing the scion with special weapon from the militarum tempestus scions and any scion from the militarum tempestus command squad, the added soldier has an hot-shot volley gun who cannot be deselected.

**Comment by alphalas** [comment] 2017-06-19 20:55
duplicate of #218

**Closed as completed by alphalas** 2017-06-19 20:55 UTC
Labels: ✔ Res: duplicate, 💾 Cat: Imperium - Astra Militarum, Area: validation
