### ISSUE TITLE
[Anon] Bug report: Imperium - Adeptus Mechanicus.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11486] opened 2022-06-28 06:49 UTC
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Pteraxii Sterylizor Alpha Host of the Intermediary prompts error window of: Alpha has 1 too many selections from the Skitarii Warlord Traits (maximum 0).

**Comment by Mad-Spy** [comment] 2022-06-28 07:38
Duplicate of #11459

**Closed as completed by Mad-Spy** 2022-06-28 07:38 UTC
