### ISSUE TITLE
T'au Empire - Coldstar default weapons validation issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7820] opened 2020-08-04 05:26 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Coldstar doesn't have required misslepod, but reads as missing of removed.

**Comment by amis92** [comment] 2020-08-04 08:22
Duplicate of #2936

**Closed as completed by amis92** 2020-08-04 08:22 UTC
Labels: ✔ Res: duplicate, 💾 Cat: T'au Empire, Area: validation, Type: bug
