### ISSUE TITLE
FW Adeptus Astartes: Storm bolter on Sicaran Arcus should cost 5pts

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10712] opened 2021-11-25 22:48 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Dear developer. 
First of all a huge thank you for your work. 
One small mistake if I may. 
For the Sicaran Arcus Tank. Heavy support. FW Imperium. 
In my blood angels list. 
The Storm Bolter option should cost 5 points and be free as it is now. 
Thank you !

**Comment by Mad-Spy** [comment] 2021-11-28 15:51
Duplicate of #10595

**Closed as completed by Mad-Spy** 2021-11-28 15:51 UTC
Labels: Area: costs, 💾 Lib: Imperium - FW Adeptus Astartes, Type: bug
