### ISSUE TITLE
[Anon] Bug report: Imperium - Ultramarines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8660] opened 2020-11-04 22:55 UTC
**File:** Imperium - Ultramarines.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Thank you for the Space Marine Update. The Chapter Master is missing a Storm Shield option. The Storm Bolter can also be replaced with a Storm Shield.

**Comment by Mad-Spy** [comment] 2020-11-05 09:22
There is no such model as a "Chapter Master". Chapter Master is an upgrade for multiple CAPTAIN models. However, given your reference to a storm bolter (which can only be taken on a Captain in Terminator Armour), this is probably a duplicate of #8610

**Closed as completed by Mad-Spy** 2020-11-05 09:22 UTC
