### ISSUE TITLE
[Anon] Bug report: Imperium - Iron Hands.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12610] opened 2023-03-19 17:28 UTC
**File:** Imperium - Iron Hands.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** When adding a dreadnought into an army list and selecting the 'march of the ancients' strategem checkbox it no longer allows you to also then select "hero of the chapter" strategem.  The option for it does not appear.  This was working in the previous version.  Since the dreadnought is now a character hero of the chapter should apply but it does not give you the option making you miss out on giving it warlord traits.

**Comment by AbonShell** [comment] 2023-03-19 18:13
Duplicate of #12609

**Closed as completed by AbonShell** 2023-03-19 18:13 UTC
