### ISSUE TITLE
[Anon] Bug report: Aeldari - Craftworlds.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8915] opened 2020-11-30 13:10 UTC
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** In Craftworld, Fast Attack, for the Hornet, we can't choose the weapon loadout, only the Shuriken canon is available and the cost is wrong.
Here are the options :
-shuriken canon 5pts
-starcanon 5pts
-hornet pulse laser 5pts
-Aeldary Missile Launcher 10pts
-Bright Lance 10pts

**Comment by Technoblazed** [comment] 2020-11-30 13:13
Dupe of https://github.com/BSData/wh40k/issues/8882.

The current datasheet is correct, you can't swap the pulse lasers to a different heavy weapon because it doesn't have any pulse lasers to swap out.

**Closed as completed by Technoblazed** 2020-11-30 13:13 UTC
