### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7692] opened 2020-07-30 02:13 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** In the Space Wolves version of Hellblaster units the points cost of their weapons have the 8th edition cost of 15, where for 9th it should be 0.

**Comment by williamcaw** [comment] 2020-07-30 03:09
dupe of #7689

**Comment by Mad-Spy** [comment] 2020-07-30 07:58
Duplicate of #7689

**Closed as completed** 2020-07-30 07:58 UTC
Labels: ✔ Res: duplicate
