### ISSUE TITLE
Bullgryn bone'eads and scions non-sensical weapon options or restrictions

### ISSUE THREAD

**Issue by GuillermoDiazGarcia** [BSData/wh40k-9e#9102] opened 2020-12-27 11:21 UTC
**File/Catalogue:** Astra Militarum

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:**
Bullgryn bone'ead can only use shields, both as a weapon and as a shield
Any scions that can have special weapons (both in the troops squad and in the command squad) give errors if you choose anything that isn't a volley gun
Also, volley guns appear as 7p, which should be 5p (it was correct in previous patches)

**Comment by Technoblazed** [comment] 2020-12-27 11:23
Dupe of https://github.com/BSData/wh40k/issues/9095

**Closed as completed by Technoblazed** 2020-12-27 11:23 UTC
