### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8939] opened 2020-12-02 00:33 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When legends/ index is selected Doomglaive Dreadnought does not appear in Grey Knights elite slot.

**Comment by Mad-Spy** [comment] 2020-12-02 14:40
Duplicate of #8928

**Closed as completed by Mad-Spy** 2020-12-02 14:40 UTC
