### ISSUE TITLE
[Anon] Bug report: Chaos - Thousand Sons.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12265] opened 2023-01-16 17:53 UTC
**File:** Chaos - Thousand Sons.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The wargear on Tzaangors should all be free, but Brayhorn is still 10 points, and Herd Banner is still 5 points.

**Comment by Mad-Spy** [comment] 2023-01-16 20:17
Duplicate of #12150

**Closed as completed by Mad-Spy** 2023-01-16 20:17 UTC
