### ISSUE TITLE
[Anon] Bug report: Imperium - Blood Angels.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#484] opened 2017-06-26 21:42 UTC
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** No

**Description:** Regular Dreadnought units throw an error when you equip them with 2 twin autocannons.  As far as I can see, there is nothing prohibiting that in 8th edition.

**Comment by Crowbar90** [comment] 2017-06-27 08:35
Duplicate of #460.

**Closed as completed by Crowbar90** 2017-06-27 08:35 UTC
Labels: ✔ Res: duplicate, Area: selections, 💾 Cat: Imperium - Blood Angels
