### ISSUE TITLE
Infantry/Heavy weapon heavy bolter incorrect points

### ISSUE THREAD

**Issue by lotlp** [BSData/wh40k-9e#263] opened 2017-06-19 22:53 UTC
**File:** Imperium - Astra Militarum.catz (v12)

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** No

**Description:** Heavy bolters for heavy weapon teams/infantry squads cost 10 points, should be 8.

**Comment by alphalas** [comment] 2017-06-19 22:59
Duplicate of #231

**Closed as completed by alphalas** 2017-06-19 22:59 UTC
Labels: Area: costs, ✔ Res: duplicate, 💾 Cat: Imperium - Astra Militarum
