### ISSUE TITLE
Aeldari - Craftworlds - Hornet weapon selection issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8970] opened 2020-12-05 13:52 UTC
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Aeldari Forge world Hornets do not have weapon options when under the units profile. It only has shuriken cannons and cannot be changed. There should be militiamen options to choose from like Eldar missile launchers, scatter lasers, pulse lasers, and bright lances. Really appreciate you looking into this. I’ve been keeping and eye on the updates and I’ve not see any thing posted on these being missing as of yet. I hope this can be addressed for the next update. 

Thank you.

**Comment by Valorcalls** [comment] 2020-12-05 23:16
Duplicate of #8957
#8947
#8879
#8856
#8882
#8915
#8929

**Closed as completed by Valorcalls** 2020-12-05 23:16 UTC
Labels: ✔ Res: duplicate, ✔ Res: invalid, Area: selections, 💾 Cat: Aeldari - Craftworlds, Type: bug
