### ISSUE TITLE
[Anon] Bug report: Orks - 2021.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10399] opened 2021-08-30 03:12 UTC
**File:** Orks - 2021.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Nobz, Nob with WAAAGH! Banner and Meganobz still appear with the “Keepin’ Order” rule in Orks 2021.  They no longer have this rule in the 2021 Codex and it should be removed.

**Comment by AbonShell** [comment] 2021-08-30 03:29
Duplicate of #10391

**Closed as completed** 2021-08-30 12:01 UTC
