### ISSUE TITLE
Tyranids: Issues with WLTs and Adaptive Physiology

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10805] opened 2022-01-13 05:22 UTC
**File:** Tyranids.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Tyranids Roster data. Currently it allows you to take too many Warlord traits (WLT) and Adaptive Physiology's (AP) without an error notification. With all the stratagems for extra warlord traits and Adaptive physiologies the max should be - 1 WLT + 1 Leviethan WLT + 1AP or 1 WLT + 2xAP . It is the same on my android tablet.

**Comment by GenWilhelm** [comment] 2022-01-17 10:32
Duplicate of #10803

**Closed as completed by GenWilhelm** 2022-01-17 10:32 UTC
Labels: ✔ Res: duplicate, 💾 Cat: Tyranids, Area: validation, Type: bug
