### ISSUE TITLE
[Anon] Bug report: Necrons.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#23] opened 2017-06-16 14:16 UTC
**File:** Necrons.catz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** No

**Description:** The point value for 20 man necron warriors squad should be 12 pl but is listed at 16 pl.

**Comment by Kohato** [comment] 2017-06-16 22:05
Duplicate of #22

**Closed as completed by Kohato** 2017-06-16 22:05 UTC
Labels: ✔ Res: duplicate, 💾 Cat: Necrons
