### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10996] opened 2022-02-22 17:47 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Eliminators are power level 5
Should be power level 4

**Comment by williamcaw** [comment] 2022-02-22 17:53
dupe of #10952

**Closed as completed** 2022-02-22 18:05 UTC
