### ISSUE TITLE
[Anon] Bug report: Imperium - Adepta Sororitas.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7567] opened 2020-07-28 00:27 UTC
**File:** Imperium - Adepta Sororitas.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Sisters of battle storm bolters say 4 points. They should be 3 points as per chapter approved.

**Comment by williamcaw** [comment] 2020-07-28 00:30
dupe of #7434

**Closed as completed** 2020-07-28 01:39 UTC
