### ISSUE TITLE
[Anon] Bug report: Aeldari - Drukhari.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9687] opened 2021-04-06 14:16 UTC
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Transports lack the choice of coven in the faction selection

**Comment by Valorcalls** [comment] 2021-04-06 15:48
Duplicate of #9680

**Closed as completed by Valorcalls** 2021-04-06 15:48 UTC
