### ISSUE TITLE
Death Guard: Multi Melta + Missile launcher cost incorrect

### ISSUE THREAD

**Issue by ShaneRing11** [BSData/wh40k-9e#8593] opened 2020-11-01 06:03 UTC
**File/Catalogue:** Death Guard v102

**BattleScribe version:** 2.03.25.338

**Platform:** Android

**Dropbox:** Yes

**Description:** Multi Melta cost should be 25 (currently 20), missile launcher should cost 20 (currently 15).

**Comment by Mad-Spy** [comment] 2020-11-01 18:35
As you haven't actually said what unit this is on, I'm going to assume it's a duplicate of #8454

**Closed as completed by Mad-Spy** 2020-11-01 18:35 UTC
Labels: Area: costs, 💾 Cat: Chaos - Death Guard, Type: bug
