### ISSUE TITLE
Aeldari - Craftworlds - Hornets can not bring appropriate weapons.

### ISSUE THREAD

**Issue by Jeremy-E-Johnson** [BSData/wh40k-9e#8929] opened 2020-12-01 15:39 UTC
**File/Catalogue:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** In Craftworld, Fast-Attack, Hornet unit does not allow for any non-shuriken cannon weapons to be chosen.
This should allow 2 from a list of weapons, but only allows two from the singleton list of shuriken cannnon.
Note Hornets were updated with new forge-world book. Changes include 
 - some points adjustments (including to weapon loadouts, though this looks to be updated in the file)
 - lightning assault change (already updated and visible as correct in battlescribe)
 - change to the profile of the hornet pulse lasers (Heavy 3 -> Heavy 2 and S6 -> S7). 
The last of which I did not see represented in the data file.

**Comment by Technoblazed** [comment] 2020-12-01 16:05
Dupe of:

https://github.com/BSData/wh40k/issues/8879
https://github.com/BSData/wh40k/issues/8856
https://github.com/BSData/wh40k/issues/8882
https://github.com/BSData/wh40k/issues/8915

**Closed as completed by Technoblazed** 2020-12-01 16:05 UTC
