### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9567] opened 2021-03-08 09:27 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Space Wolves (and all Space Marine files; excluding Black Templars of course.) do not allow selection of a power from another discipline when taking the Tome of Malcador Relic. RAW it allows you to take select another power from ANY discipline you have access to; not only your CHOSEN discipline. Nothing RAW prevents this, and the FAQ for 8th ruled in favor of this as well (albeit the wording was different) which hints it is also likely RAI. Only WTC doesn't allow this, all other major tournaments do.2

**Comment by Valorcalls** [comment] 2021-03-08 09:32
Duplicate of #9545

**Closed as completed by Valorcalls** 2021-03-08 09:32 UTC
