### ISSUE TITLE
[Anon] Bug report: Tyranids.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12352] opened 2023-01-24 14:04 UTC
**File:** Tyranids.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Tyranids v115 - Arks of Omen Detatchemt
Configuration : 

Missing HEROIC SUPPORT 1CP
Core Stratagem – Requisition Stratagem.

**Comment by Mad-Spy** [comment] 2023-01-24 14:08
Duplicate of #12148

**Closed as completed by Mad-Spy** 2023-01-24 14:08 UTC
