### ISSUE TITLE
Blood Angels HQ can't be given Relics of Baal

### ISSUE THREAD

**Issue by zelunwanderer** [BSData/wh40k-9e#9773] opened 2021-04-29 20:31 UTC
**File/Catalogue:** 
Adeptus Astartes Blood Angels v220

**BattleScribe version:** 2.03.25.338

**Platform:** android

**Dropbox:** Yes/No

**Description:** 
Setup: The chapter selector added to configuration and set to blood angels.  Hq added and assigned as warlord.

Issue: generic hq (checked captain, primaris tech marine, sanguinary priest) don't have an option to be given a relic of Baal

**Comment by Technoblazed** [comment] 2021-04-29 20:34
Duplicate of https://github.com/BSData/wh40k/issues/9772. Resolved in next release.

**Closed as completed by Technoblazed** 2021-04-29 20:34 UTC
Labels: ✔ Res: duplicate
