### ISSUE TITLE
Blood Angels - Sanguinary Priest missing "Hero of the Chapter" stratagem

### ISSUE THREAD

**Issue by FloYoung** [BSData/wh40k-9e#8598] opened 2020-11-01 13:58 UTC
**File/Catalogue:** Imperium - Adeptus Astartes - Blood Angels

**BattleScribe version:** 2.03.

**Platform:** Mac

**Dropbox:** No

**Description:** Sanguinary Priest missing "Hero of the Chapter" stratagem

**Comment by Mad-Spy** [comment] 2020-11-02 17:11
Duplicate of #8515

**Closed as completed by Mad-Spy** 2020-11-02 17:11 UTC
Labels: Area: selections, 💾 Cat: Imperium - Blood Angels, Type: bug
