### ISSUE TITLE
Imperium - Astra Militarum: A couple of issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#264] opened 2017-06-19 23:15 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** No

**Description:** Errors with the following:

1) Taurox Prime Two Hot Shot Volley Guns only counting for 9 Points total when it should be 9 points per HSVG (18 points total).
2) Command Squad counting as HQ when they've been moved to Elites. Also having issues with the number of lasguns having an error with the Command Squad. Says Veteran has too many selections from Lasgun (maximum 1).

**Comment by alphalas** [comment] 2017-06-19 23:24
Duplicate of #231

**Closed as completed by alphalas** 2017-06-19 23:24 UTC
Labels: Area: costs, ✔ Res: duplicate, 💾 Cat: Imperium - Astra Militarum, Area: validation
