### ISSUE TITLE
[Anon] Bug report: Imperium - Dark Angels.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7662] opened 2020-07-29 12:32 UTC
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The Point cost for Dark Angels Ravenwing Darkshroud seem to be wrong, according to the latest Munitorium a Darkshroud (120pts) with a Heavy Bolter (15pts) should be a total of 135pts, on both the android app and the windows versions it is 143pts.  Thank you for looking at this!

**Comment by Mad-Spy** [comment] 2020-07-29 14:14
Duplicate of #7657

**Closed as completed by Mad-Spy** 2020-07-29 14:14 UTC
Labels: Area: costs, ✔ Res: duplicate, 💾 Cat: Imperium - Dark Angels
