### ISSUE TITLE
Leagues of Votann: Hernkyn Pioneer Heavy weapon choices and Void Armor incorrect.

### ISSUE THREAD

**Issue by OneTrueCorvid** [BSData/wh40k-9e#11893] opened 2022-09-28 16:30 UTC
What it says on the title. 

Taking a Hernkyn Pioneer with one of the Heavy weapons (HYLas Rotary Cannon/Ion Beamer) removes the Magna-Coil Autocannon from that model, even though the Codex says otherwise. 

Likewise, Void Armor on Battlescribe says no re-roll hits or wounds. In the codex it's no re-roll wounds or damage.

**Comment by Mad-Spy** [comment] 2022-09-28 17:55
1. Looks like I misread that bullet point.
2. Duplicate of #11891

**Closed as completed** 2022-09-28 22:33 UTC
