### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11572] opened 2022-07-05 13:33 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Chaos Bikers does not allow for a Biker to be equipped with both a chainsword and a special/combi weapon.
In the Codex: Chaos Space Marines, on page 165, it says in wargear options for Chaos Bikers, it says any number of Chaos Bikers can replace their bolt pistol with 1 Astartes chainsword. In a separate bullet, it also says that up to 2 Chaos Bikers can each either be equipped with 1 special weapon or have their combi-bolter be replaced with a different combi weapon. This should imply that a Chaos Biker can be equipped with a flamer and additionally can replace his bolt pistol with a chainsword.
When a Chaos biker with special/combi weapon is added to the unit, it doesn't give the option to replace their bolt pistol with a chainsword. Additionally, it doesn't even show that the biker with the special/combi weapon has a bolt pistol equipped.

**Comment by Mad-Spy** [comment] 2022-07-05 14:42
Fixed in next release. Duplicate of #11566

**Closed as completed by Mad-Spy** 2022-07-05 14:42 UTC
