### ISSUE TITLE
Imperium - Adepta Sororitas v117 Incomplete Order Conviction, incorrect CP cost for Battle Sanctum

### ISSUE THREAD

**Issue by EricSmailys** [BSData/wh40k-9e#7875] opened 2020-08-09 03:47 UTC
**File/Catalogue:** Imperium - Adepta Sororitas v117 

**BattleScribe version:** 2.03.21.166

**Platform:** Windows 10

**Dropbox:** No

**Description:** When selecting the Sacred Rose Order Conviction, the rules text only lists the first of three benefits - automatically passing Combat Attrition tests. The other two - regaining Miracle dice on a 5+ and hitting on Overwatch with 5s and 6s - were not removed by the FAQ, only the first part was modified (as shown in the Warhammer 40K App).

When adding a Fortification Network and selecting the Battle Sanctum for an army with an Adeptus Ministorum Warlord (such as any Warlord from the Adepta Sororitas army list), the Detachment should give a command bonus refund of 1CP for the matching faction keyword. The Detachment CP does not automatically update as it does for the primary detachment.

**Comment by Technoblazed** [comment] 2020-08-10 12:40
First issue is a duplicate of https://github.com/BSData/wh40k/issues/7862. 

In regards to the fortification network, if you click the `Detachment CP` option, then the `Command Benefit` on the right hand side, it will give you the CP back.

**Closed as completed by Technoblazed** 2020-08-10 12:40 UTC
Labels: Area: costs, ✔ Res: duplicate, ✔ Res: by design, 💾 Cat: Imperium - Adepta Sororitas, Type: bug
