### ISSUE TITLE
Wraithlord support weapons is missing shuriken catapult from 'Flamer and Shuriken Catapult' option

### ISSUE THREAD

**Issue by neonsamurai** [BSData/wh40k-9e#12515] opened 2023-02-20 08:09 UTC
I apologise for reposting, but I think my previous issue was closed prematurely. 

The configuration of the Wraithlord looks like this:
![Bildschirm­foto 2023-02-19 um 23 05 55](https://user-images.githubusercontent.com/1582455/219977941-09ac6a4d-7d7c-415a-9f17-87389db2d10f.png)

When looking at the Roster preview it does not show shuriken catapults:
![Bildschirm­foto 2023-02-19 um 23 07 27](https://user-images.githubusercontent.com/1582455/219977980-ea98274a-88a1-4d29-887f-fed43791c46e.png)

However I noticed in the data editor, that the shuriken catapult is missing from the wraithlord's corresponding Support Weapon Configuration:
![Bildschirm­foto 2023-02-19 um 23 08 39](https://user-images.githubusercontent.com/1582455/219978032-819597dc-4eb4-426a-b223-ad8e1c12f905.png)

And when I added the shuriken catapult to the profile in the data editor, it would show up correctly on the roster. I think I could provide a pull request with the fix, if that helps.

_Originally posted by @neonsamurai in https://github.com/BSData/wh40k/issues/12510#issuecomment-1436110635_

**Comment by Mad-Spy** [comment] 2023-02-20 09:33
Duplicate of #12510

**Closed as completed by Mad-Spy** 2023-02-20 09:33 UTC
