### ISSUE TITLE
[Anon] Bug report: Imperium - Deathwatch.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7700] opened 2020-07-30 10:56 UTC
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Deathwatch missing: Primaris Captain (Indomitus), Primaris Lieutenant (Indomitus), Assault Intercessors, Bladeguard Veterans, Bladeguard Ancient, Justicar, Outriders, Eradicators

**Comment by Technoblazed** [comment] 2020-07-30 19:55
Duplicate of https://github.com/BSData/wh40k/issues/7496

**Closed as completed** 2020-07-30 20:05 UTC
Labels: ✔ Res: duplicate
