### ISSUE TITLE
[Anon] Bug report: Imperium - Dark Angels.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9476] opened 2021-02-17 03:41 UTC
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Relic contemptor dreadnought base point is not 15 .

**Comment by Valorcalls** [comment] 2021-02-17 03:42
Duplicate of numerous reports

**Closed as completed by Valorcalls** 2021-02-17 03:42 UTC
Labels: ✔ Res: duplicate
