### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7897] opened 2020-08-10 15:26 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Rough riders and legends astra militarum loadouts do not have the [Legends] tag.

**Comment by DrTobogganMD** [comment] 2020-08-10 16:05
Duplicate of 7883

**Closed as completed by DrTobogganMD** 2020-08-10 16:05 UTC
