### ISSUE TITLE
[Anon] Bug report: Imperium - Raven Guard.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9968] opened 2021-06-08 14:28 UTC
**File:** Imperium - Raven Guard.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The Las Fusil on the Eliminator Sergeant costs 10 points but should be reduced to 5.

**Comment by Mad-Spy** [comment] 2021-06-08 14:29
Duplicate of #9964

**Closed as completed by Mad-Spy** 2021-06-08 14:29 UTC
