### ISSUE TITLE
[Anon] Bug report: Imperium - Adeptus Ministorum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#249] opened 2017-06-19 16:59 UTC
**File:** Imperium - Adeptus Ministorum.catz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** No

**Description:** Tempestor command squad. 
When adding a basic scion he incorrectly comes with a hot shot volley gun. Which you can't get rid of. 
If you add a special weapon you somehow get 2 hot Shot lasguns a hot shot volley gun and the special weapon. When it should just be the special weapon.

**Comment by alphalas** [comment] 2017-06-19 20:54
duplicate of #218

**Closed as completed by alphalas** 2017-06-19 20:54 UTC
Labels: ✔ Res: duplicate, Area: selections, 💾 Cat: Imperium - Adepta Sororitas
