### ISSUE TITLE
[Anon] Bug report: Necrons.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12246] opened 2023-01-16 02:12 UTC
**File:** Necrons.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Necron Annihilation Cult doesn't show up in 'Dynasty Choice' and 'Army of Renown' is missing from Game Configuration.

**Comment by WindstormSCR** [comment] 2023-01-16 11:40
duplicate of #12164

**Closed as completed by WindstormSCR** 2023-01-16 11:40 UTC
