### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12537] opened 2023-02-24 17:10 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Adeptus Mechanicus' Belisarius Cawl, as per one of the latest Ark of Omens FAQs reguarding supreme commanders, is now able to be taken in any forgeworld not just Mars. The only catch is that Cawl himself does not benefit from other forge world's dogmas. Cawl is still a hidden unit when building lists in other forge worlds and should be listed and available for building. I don't know how hard it'd be but it would be nice to have somewhere in the datasheets for other forge worlds a reminder the Cawl will not benefit from non-Mars dogmas. Ty

**Comment by AbonShell** [comment] 2023-02-24 17:34
Duplicate of #12538

**Closed as completed by AbonShell** 2023-02-24 17:34 UTC
