### ISSUE TITLE
Imperium - Blood Angels: Tome of Malcador doesn't give extra power.

### ISSUE THREAD

**Issue by khinzaw** [BSData/wh40k-9e#8718] opened 2020-11-09 07:56 UTC
When selecting the Tome of Malcador relic it doesn't seem to actually increase the cap on psychic powers and selecting an extra one will still prompt the error.

**Comment by Mad-Spy** [comment] 2020-11-09 08:44
Please be more specific about your issue with the Tome. It appears to be working correctly.

**Comment by khinzaw** [comment] 2020-11-09 09:33
> Please be more specific about your issue with the Tome. It appears to be working correctly.

A regular librarian knows 2 powers from the librarius discipline correct? Well the tome should be allowing me to take a third, but selecting a third triggers the "librarian has 1 too many selections from Disciplines (maximum 2)" error.

**Comment by acebaur** [comment] 2020-11-09 12:08
Not replicating this. What chapter are you using? Also the terminator Sgt can't change is loadout, so that is working as intended.

**Comment by khinzaw** [comment] 2020-11-09 13:57
> Not replicating this. What chapter are you using? Also the terminator Sgt can't change is loadout, so that is working as intended.

I am using Blood Angels. Here is an image link: https://i.gyazo.com/2e2a736036f462abf2dc04da959b0d66.png

Also, whoops I guess I missed the wording was specifically replace power fists.

**Comment by Mad-Spy** [comment] 2020-11-09 15:36
It's a Blood Angels specific issue. Reassigned.

**Comment by Dunamis55** [comment] 2020-11-12 01:46
Consolidated into #8753

**Closed as completed by Dunamis55** 2020-11-12 01:46 UTC
Labels: Area: selections, 💾 Cat: Imperium - Blood Angels, Type: bug
