### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9249] opened 2021-01-15 16:55 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Primaris Chaplain on Bike is missing the Turbo-boost ability.

**Comment by Technoblazed** [comment] 2021-01-15 17:54
Dupe of https://github.com/BSData/wh40k/issues/9248

**Closed as completed by Technoblazed** 2021-01-15 17:54 UTC
