### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7742] opened 2020-07-31 10:09 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Warlord validation has an issue when using unbound army lists. With no warlord selected I get a requires warlord message, but when I select one it says I have too many. I checked a couple other catalogs and it looks like this is just in space wolves.

**Comment by Mad-Spy** [comment] 2020-07-31 10:11
Duplicate of #7737

**Closed as completed by Mad-Spy** 2020-07-31 10:11 UTC
