### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11734] opened 2022-07-30 07:47 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 9.06.03

**Platform:** Android

**Dropbox:** No

**Description:** Kharn the betrayer HQ missing the ability blood for the blood god.

**Comment by Mad-Spy** [comment] 2022-07-30 10:18
Duplicate of #11732

**Closed as completed by Mad-Spy** 2022-07-30 10:18 UTC
