### ISSUE TITLE
[Anon] Bug report: Imperium - Ultramarines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10904] opened 2022-02-03 08:17 UTC
**File:** Imperium - Ultramarines.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** In Captain in Gravis Armor, under Weapon Options the three options currently listed are Astartes Chainsword, Master-crafted power sword and Power sword. What it should be is Astartes Chainsword, Power sword and Power fist with the correct weapon profiles to go along with them.

**Comment by Mad-Spy** [comment] 2022-02-03 10:02
Duplicate of #10892

**Closed as completed by Mad-Spy** 2022-02-03 10:02 UTC
