### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9382] opened 2021-02-04 06:05 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.21

**Platform:** Mac

**Dropbox:** No

**Description:** I'm getting an error whenever i add an special weapons that isnt a sniper rifle to an Guardsmen squad. Error reads - "Guardsmen W/ Special Weapon must have 1 more selections of sniper rifles (minimum 1).

**Comment by Technoblazed** [comment] 2021-02-04 06:09
Duplicate of #9342

**Closed as completed by Technoblazed** 2021-02-04 06:09 UTC
