### ISSUE TITLE
Bug Deathwatch points and Indomitus

### ISSUE THREAD

**Issue by Drakamas** [BSData/wh40k-9e#7451] opened 2020-07-27 07:19 UTC
**File/Catalogue:** Deathwatch

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Stalker bolt rifles are incorrectly listed as 1pts instead of 0pts. All new Indomitus options are missing.

**Comment by Thairne** [comment] 2020-07-27 13:39
Duplicate of #7461

**Closed as completed by Thairne** 2020-07-27 13:39 UTC
