### ISSUE TITLE
Imperium - Adeptus Mechanicus

### ISSUE THREAD

**Issue by new-neon** [BSData/wh40k-9e#234] opened 2017-06-19 12:50 UTC
**File/Catalogue:** Imperium - Adeptus Mechanicus v4

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Description:** 
1) Skitarii Rangers and Skitarii Vanguards with special weapons have incorrect price, must be  more expensive by 10 pts (because default weapon cost 0)
2) I add unit of Skitarii Rangers or Skitarii Vanguards and set count of models with standard weapon to 2, add 2 with special (plasma for example) all good. But when i make some changes to alfa in this squad (add some CCW for example) BattleScribe start incorrect counting of maximum special weapons and say show notify.

**Comment by Thairne** [comment] 2017-06-19 13:59
1. fixed with latest release
2. cannot reproduce. You need to toggle away the Radium Carbine.

**Comment by new-neon** [comment] 2017-06-20 09:27
![screen](https://user-images.githubusercontent.com/9164428/27326245-a381f840-55b3-11e7-9a41-62bc5c8b3a24.png)
![screen2](https://user-images.githubusercontent.com/9164428/27326328-d14b346c-55b3-11e7-82d3-521674c446c5.png)

**Comment by Thairne** [comment] 2017-06-20 09:37
![grafik](https://user-images.githubusercontent.com/8590840/27326824-dfd691cc-55ac-11e7-92b3-d7ec7c3d4c27.png)
![grafik](https://user-images.githubusercontent.com/8590840/27326832-e346e62c-55ac-11e7-82e0-3dfb99f44319.png)

**Comment by Thairne** [comment] 2017-06-20 09:39
Might be something I fixed earlier.
A release was pushed about 30 minutes ago.

**Closed as completed** 2017-06-20 19:50 UTC
Labels: ✔ Res: wontfix, Area: BattleScribe app

**Comment by Thairne** [comment] 2017-06-20 19:57
If @Jonskichov ever looks here:
Removing shared? from repeatable modifiers fixed this issue.
It SHOULD not, but it did it.
There is some weird interaction.

Documenting:

![grafik](https://user-images.githubusercontent.com/8590840/27353008-e6300b38-5602-11e7-9db8-8827362c4afb.png)

This is the unit in roster view.
The goal is to have a max of 2 in total for special weapons.
That is implemented this way:

![grafik](https://user-images.githubusercontent.com/8590840/27353061-0de36936-5603-11e7-9a18-c4b1fe13aef5.png)

This does the trick.
However is Shared? is checked on the repeatable modifiers, selecting a different loadout for the Alpha entry breaks the constraints as seen above.
However the Alpha has unrelated wargear with different ID's that do not exist somewhere else in the ancestor entry (except the Galvanic Rifle which is the standard weapon for this model).

![grafik](https://user-images.githubusercontent.com/8590840/27353167-5ffd5d3a-5603-11e7-9699-9f6e9c911766.png)

The modifiers for pistols do not cause the issue (it seems) since changing out for melee weapons breaks the constraints too. There is no modifier that could change max on the special weapons based on the Alphas loadout...
