### ISSUE TITLE
Thousand sons Artifacts not showing up

### ISSUE THREAD

**Issue by Ithyrrinaz** [BSData/wh40k-9e#10320] opened 2021-08-17 21:05 UTC
**File/Catalogue:** Thousand sons

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** The artifacts "incandaeum" and "Skaelochs Talon" should be available to ALL Force stave users. As it is now its not select-able.  Nor does it show up in the list of artifacts..

**Comment by Mad-Spy** [comment] 2021-08-17 21:30
Duplicate of #10319

**Closed as completed by Mad-Spy** 2021-08-17 21:30 UTC
