### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Knights.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11330] opened 2022-05-30 15:20 UTC
**File:** Chaos - Chaos Knights.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Even after update, single dreadblade in super heavy Auxiliary detachment still does not show fell bond in unit description page.i can choose one, but it doesn't show up.

**Comment by Mad-Spy** [comment] 2022-05-30 15:41
Duplicate of #11301

**Closed as completed by Mad-Spy** 2022-05-30 15:41 UTC
