### ISSUE TITLE
[Anon] Bug report: Aeldari - Ynnari.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#274] opened 2017-06-20 02:29 UTC
**File:** Aeldari - Ynnari.catz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** No

**Description:** In the Ynnari (v5) Battalion Detachment (only tried this detachment, but likely a problem in others) under dedicated transports there was no option to select a Drukhari transport (Venom or Raider). If it is dependent, yes there were Drukhari infantry/HQ units selected.

**Comment by GenWilhelm** [comment] 2017-06-20 02:55
Duplicate of #113.

**Closed as completed by GenWilhelm** 2017-06-20 02:55 UTC
Labels: ✔ Res: duplicate, Area: selections, 💾 Lib: Aeldari - Aeldari Library
