### ISSUE TITLE
[Anon] Bug report: Imperium - Raven Guard.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12589] opened 2023-03-12 12:37 UTC
**File:** Imperium - Raven Guard.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** the Primaris Lieutenant has not been updated to reflect the changes made to the profile upon release of the Strike Force Agastus rules supplement.

**Comment by AbonShell** [comment] 2023-03-12 12:46
duplicate of #12577

**Closed as completed by AbonShell** 2023-03-12 12:46 UTC
