### ISSUE TITLE
Grey Knights Relics Issue

### ISSUE THREAD

**Issue by enkkii** [BSData/wh40k-9e#12349] opened 2023-01-23 22:22 UTC
Armory of Titan Stratagem allows you 1 or 2 relics depending on game size, but there is no way to also use the new Arks of Omen stratagem "Relic" for 1 CP. It should be possible to have up to 3 relics this way.

**Comment by tekton** [comment] 2023-02-02 18:04
duplicate of #12225 - will just do it all there :)

**Closed as completed by tekton** 2023-02-02 18:04 UTC
Labels: Area: selections, 💾 Cat: Imperium - Grey Knights, Type: bug
