### ISSUE TITLE
Grey Knights Squad Leader/Character Storm Bolters

### ISSUE THREAD

**Issue by nocturnal40k** [BSData/wh40k-9e#9284] opened 2021-01-22 09:43 UTC
**File/Catalogue:** Imperium - Grey Knights v75

**BattleScribe version:** 2.03.15

**Platform:** iOS

**Dropbox:** No

**Description:**

Storm bolters are displaying as free for all grey knight squad leaders and characters but their costs have not been updated to bake these costs in.

The points cost is listed as 3 points less for Justicars and Paragons and the Chaplain is listed as being 3 points cheaper than he should be. 

This applies for:

Chaplain
Brother Captain
Strike Squad Justicar
Terminator squad Justicar
Paladin Squad Paragon
Purifier Squad Knight of the Flame
Interceptor Squad Justicar
Purgation Squad Justicar

**Comment by Valorcalls** [comment] 2021-01-22 10:02
Duplicate of #9254

**Closed as completed by Valorcalls** 2021-01-22 10:02 UTC
