### ISSUE TITLE
[Anon] Bug report: Tyranids - Genestealer Cults.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12345] opened 2023-01-23 14:24 UTC
**File:** Tyranids - Genestealer Cults.catz

**BattleScribe version:** 3.25.33

**Platform:** Android

**Dropbox:** No

**Description:** Arks of Omen detachment lacks the generic relic strat, also isn't accounting for character elite slots. Currently says I have too many Elites at 7 when I have characters in elite slots with Elites as my compulsory slots

**Comment by Mad-Spy** [comment] 2023-01-23 20:40
Duplicate of #12257

**Closed as completed by Mad-Spy** 2023-01-23 20:40 UTC
Labels: Type: bug
