### ISSUE TITLE
Incorrect points - Adeptus Astartes Black Templars Thunderfire Cannon

### ISSUE THREAD

**Issue by avalaros** [BSData/wh40k-9e#7465] opened 2020-07-27 08:33 UTC
**File/Catalogue:
Warhammer 40,000 v 9.00
Imperium - Adeptus Astartes - Black Templars v12

**BattleScribe version: 2.03.15

**Platform: iOS

**Dropbox: No

**Description: 
The Heavy Support option: Thunderfire cannon is listed at 195pts but is composed of the gunplatform (85pts) + thunderfire cannon wargear (0pts) and the Techmarine Gunner (45pts) + servo harness wargear (10pts) adding to a total of 140pts, not 195pts.

**Comment by DessaiImrane** [comment] 2020-07-27 08:42
Same problem for Imperial Fist. I guess it is wrong for everyone

**Comment by Gingrel** [comment] 2020-07-27 12:22
Dupe of #7456

**Closed as completed** 2020-07-27 13:13 UTC
