### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10997] opened 2022-02-22 17:50 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Storm Speeder Thunder strike is power level 9
Should be 8

Others may be wrong as well

Tbh across all factions it looks like the latest pl update wasn't implemented

**Comment by williamcaw** [comment] 2022-02-22 17:53
dupe of #10952

**Comment by Mad-Spy** [comment] 2022-02-22 18:05
@williamcaw if you're going to comment about duplicates, can you type the whole word. That way GitHub will link the issues together.

Duplicate of #10952

**Closed as completed** 2022-02-22 18:05 UTC
