### ISSUE TITLE
[Anon] Bug report: Imperium - Ultramarines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8503] opened 2020-10-30 09:30 UTC
**File:** Imperium - Ultramarines.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** On the tab where successor chapters are chosen the tactic "stealthy" still says it works on anything more than 12" away but in the new codex this distance has been changed to 18".

**Comment by GenWilhelm** [comment] 2020-10-30 11:18
Duplicate of #8488

**Closed as completed by GenWilhelm** 2020-10-30 11:18 UTC
Labels: ✔ Res: duplicate, 💾 Lib: Imperium - Space Marines
