### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9388] opened 2021-02-05 00:35 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Any Special Weapons options have the Sniper Rifle as default and when changed to the desired weapon an incorrect error message shows stating: "x w/ Special Weapon must have 1 more selections of Sniper Rifle (minimum 1)".

**Comment by Valorcalls** [comment] 2021-02-05 00:38
Duplicate of #9342

**Closed as completed by Valorcalls** 2021-02-05 00:38 UTC
