### ISSUE TITLE
Tau Empire

### ISSUE THREAD

**Issue by relasine** [BSData/wh40k-9e#490] opened 2017-06-27 00:50 UTC
**File - Tau Empire.catz* 

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** Hazard Suits are supposed to be able to take a single support system.

**Comment by amis92** [comment] 2017-06-27 01:04
Seriously.... it's third one opened. Please do use the search feature.

Duplicate of #470

**Closed as completed by amis92** 2017-06-27 01:04 UTC
Labels: ✔ Res: duplicate, Area: selections, ✔ Res: deprecated, 💾 Cat: T'au Empire
