### ISSUE TITLE
[Anon] Bug report: Imperium - Elucidian Starstriders.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11941] opened 2022-10-19 21:15 UTC
**File:** Imperium - Elucidian Starstriders.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** outdates point values of all the units. Rotor cannon figure same points as the rest. Canid unit now has stats. OUTDATED DATA

**Comment by AbonShell** [comment] 2022-10-19 21:20
Duplicate of #11932 #11923 & #11919

**Closed as completed by AbonShell** 2022-10-19 21:20 UTC

**Comment by Mad-Spy** [comment] 2022-10-19 21:22
However, the work has been done and will be in the next release.
