### ISSUE TITLE
[Anon] Bug report: Aeldari - Drukhari.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9711] opened 2021-04-10 17:26 UTC
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Lelith Hesperax is not an elligible Master Succubus for the purposes of upgrading Wyches into Hekatrix Bloodbrides in the same detachment.

**Comment by Valorcalls** [comment] 2021-04-10 18:38
Duplicate of #9694 , #9709

**Closed as completed by Valorcalls** 2021-04-10 18:38 UTC
