### ISSUE TITLE
Heavy weapons for chaos legionaries

### ISSUE THREAD

**Issue by Jhotaro25** [BSData/wh40k-9e#11592] opened 2022-07-06 14:02 UTC
**Describe the bug**
Legionaries cant take two of the same heavy weapons

**To Reproduce**
1. Go to chaos space marine roaster
2. Click on troop
3. Scroll down to legionaries
4. See error that they can take two of the same heavy weapons

**Expected behavior**
Adjust legionaires so they may only take one of each heavy weapon
**Screenshots**
![image](https://user-images.githubusercontent.com/108304170/177568204-71694b7d-a0fa-4e32-ab07-842864341d34.png)

**Device and data (please complete the following information):**
 - OS: [iOS]
 - BattleScribe version [2.03.45]
 - Release version [e.g. v9.5.0]

**Additional context**

**Comment by Mad-Spy** [comment] 2022-07-06 14:53
Duplicate of #11576

**Closed as completed by Mad-Spy** 2022-07-06 14:53 UTC
