### ISSUE TITLE
[Anon] Bug report: Imperium - Adeptus Mechanicus.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9099] opened 2020-12-27 05:43 UTC
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 9.01.08

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Scion infantry have an alert when picking a special weapon other than a hot shot Valley gun

Astropaths have the option to take a telepathic a staff or las pistol when they have both base 

When allying in custodies the  custodies characters have no options for relic of tera when any character can pick a relic

**Comment by Valorcalls** [comment] 2020-12-27 05:57
Duplicate of #9100

**Closed as completed by Valorcalls** 2020-12-27 05:57 UTC
