### ISSUE TITLE
[Anon] Bug report: Imperium - Ultramarines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9735] opened 2021-04-22 06:47 UTC
**File:** Imperium - Ultramarines.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Exorcist chapter data is missing including no warlord traits, special equipment or strategems. Just defaults to standard vanilla ultramarines.
I am a supporter of BattleScribe.

**Comment by Mad-Spy** [comment] 2021-04-22 07:48
Duplicate of #9646

**Closed as completed by Mad-Spy** 2021-04-22 07:48 UTC
