### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7454] opened 2020-07-27 07:30 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Adepta sororitas points for stormbolter is wrong
expected 3
actual 4

**Comment by williamcaw** [comment] 2020-07-27 07:32
dupe of #7434

**Closed as completed** 2020-07-27 13:20 UTC
