### ISSUE TITLE
[Anon] Bug report: Imperium - Adeptus Mechanicus.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11480] opened 2022-06-27 17:18 UTC
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Adeptus mechanicus strategems for additional warlord traits and relics are not working correctly under the nephilim section of list building. I get validation errors and cannot add additional relics.

**Comment by Mad-Spy** [comment] 2022-06-27 21:40
Duplicate of #11459

**Closed as completed by Mad-Spy** 2022-06-27 21:40 UTC
