### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11445] opened 2022-06-26 01:32 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Centurion Devastator Squad - Sergeant has incorrect point values for heavy bolter and lascannons

**Comment by Mad-Spy** [comment] 2022-06-26 05:43
Duplicate of #11440

**Closed as completed by Mad-Spy** 2022-06-26 05:43 UTC
