### ISSUE TITLE
[Anon] Bug report: Imperium - Adeptus Custodes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10812] opened 2022-01-15 17:24 UTC
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Ther is a bug in coding on the shield captain as the sword and shield i doesn't cost 20 its a simple 10 point when being added to the captain

**Comment by williamcaw** [comment] 2022-01-15 17:33
dupe of #10811

**Comment by Technoblazed** [comment] 2022-01-15 21:34
Fixed in https://github.com/BSData/wh40k/commit/cd6e9c0c1ee9f53d13f6fa8e04edb83cc1ec8d42

**Closed as completed by Technoblazed** 2022-01-15 21:34 UTC
