### ISSUE TITLE
[Anon] Bug report: Imperium - Dark Angels.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9477] opened 2021-02-17 07:12 UTC
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Dark Angels Deathwing Strikemaster is counting as one too many HQ in the org slot, and seems to not be getting the company heroes ability where the second lieutenant doesn’t take a battlefield role slot in a deathwing vanguard detachment. Can verify by removing the strikemaster and swapping to a primaris lieutenant. That one works fine. Remove the primaris Lt and go back to the strikemaster and the error of too many HQ in the detachment returns.

**Comment by Valorcalls** [comment] 2021-02-17 07:15
Duplicate of #9445

**Closed as completed by Valorcalls** 2021-02-17 07:15 UTC
