### ISSUE TITLE
Valerian and Aleya/Talons of the Emperor

### ISSUE THREAD

**Issue by MadamMateria** [BSData/wh40k-9e#7505] opened 2020-07-27 14:51 UTC
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** With the new rules additions in War of the Spider, Sisters of Silence can now be added to Custodes detachments without penalties. You can add Sisters of Silence in the roster to the Battalion/other Detachment of Custodes, but they're obviously listed separately. As well, either Valerian and Aleya are missing, or due to their dual-faction association, are simply unselectable by either faction.

Recommended fixes: adding the Sisters of Silence directly into the Custodes data similarly to Ministorum in Sororitas, a Talons of the Emperor faction option that lists the options for both, or I guess a flag to recognize if Sister of Silence are added to Custodes to make their only HQ option available?

**Comment by williamcaw** [comment] 2020-07-27 15:50
being worked upon by  Mad-Spy dupe #7250

**Comment by Dunamis55** [comment] 2020-07-27 17:15
Duplicate of #7250

**Closed as completed by Dunamis55** 2020-07-27 17:15 UTC
