### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7814] opened 2020-08-03 21:40 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Ulrik The Slayer needs updating, as per the Official Warhammer App this character has a new datasheet with new stats, including the use of lithanies.

**Comment by Technoblazed** [comment] 2020-08-03 22:33
Duplicate of https://github.com/BSData/wh40k/issues/7799.

**Closed as completed by Technoblazed** 2020-08-03 22:33 UTC
Labels: ✔ Res: duplicate
