### ISSUE TITLE
Flesh Hounds are missing their Savage Pounce ability,

### ISSUE THREAD

**Issue by Thor-axetheImpaler** [BSData/wh40k-9e#11869] opened 2022-09-19 15:37 UTC
Flesh Hounds are missing their Savage Pounce ability.

https://www.wargamer.com/wp-content/sites/wargamer/2022/08/warhammer-40k-codex-updates-khorne-day-flesh-hounds-savage-pounce.jpg

**Comment by Mad-Spy** [comment] 2022-09-19 16:50
Duplicate of #11847

**Closed as completed by Mad-Spy** 2022-09-19 16:50 UTC
