### ISSUE TITLE
[Anon] Bug report: Aeldari - Ynnari.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#487] opened 2017-06-26 22:05 UTC
**File:** Aeldari - Ynnari.catz

**BattleScribe version:** 2.01.02

**Platform:** Mac

**Dropbox:** No

**Description:** Razorwing flocks appear to be 3+ for the minimum dimension of the unit. They should be 1-3 instead, 1-12 considering further upgrades.

**Comment by FarseerVeraenthis** [comment] 2017-06-27 09:13
Duplicate of #486 because the Ynnari CAT is a merge of the other Aeldari CAT's.
This issue will be fixed when #486 is complete.

**Closed as completed by FarseerVeraenthis** 2017-06-27 09:13 UTC
Labels: ✔ Res: duplicate, Area: selections, 💾 Lib: Aeldari - Aeldari Library
