### ISSUE TITLE
Imperium - Astra Cartographica troops mislabaled and units missing

### ISSUE THREAD

**Issue by lupislacertus** [BSData/wh40k-9e#11950] opened 2022-10-25 03:06 UTC
**Describe the bug**
This faction is not up to date. It is missing the retinue options for the rogue trader, the voidmen at arms are still labeled elites, and the Imperial Navy Breachers are not present at all.

**To Reproduce**
Attempt to make a detachment for Astra Cartographica, try and find the two troop options or the retinue options for the Rogue Trader

**Additional context**

**Comment by Mad-Spy** [comment] 2022-10-25 11:39
Fixed in next release. Duplicate of multiple other issues. Pleas ensure you check closed issues before opening new ones.

**Closed as completed by Mad-Spy** 2022-10-25 11:39 UTC
