### ISSUE TITLE
[Anon] Bug report: Orks.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10472] opened 2021-09-22 14:54 UTC
**File:** Orks.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Mozrag Skragbad has 6 Attacks, not 3. That is all.

**Comment by Mad-Spy** [comment] 2021-09-22 15:00
Duplicate of #10458

**Closed as completed by Mad-Spy** 2021-09-22 15:00 UTC
