### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#29] opened 2017-06-16 14:43 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** No

**Description:** Tactical Squads may take either a Heavy or a Special weapon at less than 10 members. Currently, a list error shows up when outfitting a marine with a heavy weapon while under full strength.

**Comment by flakpanda** [comment] 2017-06-16 19:43
Duplicate of #16.

**Closed as completed by flakpanda** 2017-06-16 19:43 UTC
Labels: ✔ Res: duplicate, 💾 Cat: Imperium - Space Marines
