### ISSUE TITLE
you cannot select the relic strategem for any GSC characters

### ISSUE THREAD

**Issue by Carpathea1989** [BSData/wh40k-9e#12365] opened 2023-01-25 17:12 UTC
File: Imperium - GenestealerCults.catz

BattleScribe version: 2.03.21

Platform: Windows

Dropbox: No

Description: you cannot select the relic strategem for any GSC characters or elite characters.

**Comment by Mad-Spy** [comment] 2023-01-25 21:04
Duplicate of #12257

**Closed as completed by Mad-Spy** 2023-01-25 21:04 UTC
Labels: 💾 Cat: Tyranids - Genestealer Cults
