### ISSUE TITLE
[Anon] Bug report: Aeldari - Craftworlds.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7531] opened 2020-07-27 17:22 UTC
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Autarch power sword is showing as 5 points. It should be 0 points for all autarchs. Additionally when selecting a yenarri detachment it gives an error asking for another warlord if you dont have one of the yenarri characters as the warlord.

**Comment by KalChoedan** [comment] 2020-07-27 17:30
Duplicate of #7403 and #7351

**Comment by Dunamis55** [comment] 2020-07-27 18:16
As stated above, duplicate of #7403 and #7351

**Closed as completed by Dunamis55** 2020-07-27 18:16 UTC
