### ISSUE TITLE
[Anon] Bug report: T'au Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8074] opened 2020-09-02 15:27 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Changing base weapons of Coldstar Commander counts as error, while codex says what I can do this

**Comment by Technoblazed** [comment] 2020-09-02 15:30
Assuming you're talking to about the HOBC/missile pod:

- A missile pod is required with a HOBC for coldstar. You replace both, not one.

Duplicate of #2936 with all the information you need over there.

**Closed as completed by Technoblazed** 2020-09-02 15:30 UTC
Labels: ✔ Res: duplicate, Area: selections, 💾 Cat: T'au Empire
