### ISSUE TITLE
[Anon] Bug report: Chaos - Death Guard.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9324] opened 2021-01-27 03:11 UTC
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Deathguard
Blightlord terminators wargear bubonic axe shows that it is +1 str but it around read +2 str.

**Comment by Valorcalls** [comment] 2021-01-27 03:12
Duplicate of #9300 #9308 #9322

**Closed as completed by Valorcalls** 2021-01-27 03:12 UTC
