### ISSUE TITLE
[Anon] Bug report: Aeldari - Craftworlds.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8041] opened 2020-08-26 23:15 UTC
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Unable to choose Ynarri warlord correctly with the new 9th edition. This goes for craftworlds, Drukhari and harlequins. Additionally, Strategem exalted of undead which allows an extra warlord trait also does not work for any of the three factions

**Comment by DrTobogganMD** [comment] 2020-08-26 23:33
Duplicate of #7351  ... and like 3 others.

**Closed as completed by DrTobogganMD** 2020-08-26 23:33 UTC
Labels: ✔ Res: duplicate
