### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11876] opened 2022-09-20 18:30 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Manticores and Basilisks no longer have the ability to select a tank ace “full payload”

**Comment by AbonShell** [comment] 2022-09-20 18:32
Duplicate of #11852

**Closed as completed by AbonShell** 2022-09-20 18:32 UTC
