### ISSUE TITLE
Ultramarines - Victrix Honour Guard

### ISSUE THREAD

**Issue by ASHC2486** [BSData/wh40k-9e#8403] opened 2020-10-29 08:25 UTC
**File/Catalogue:** Imperium - Ultramarines

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Victrix Honour Guard should not have the Storm Shield rule. They should instead have the Ultima Storm Shield rule, which remains the old Storm Shield (a 3++ instead of 4++/+1 to armour saves). Note: This was specifically singled out in the Ultramarines FAQ. In the Designer's Notes: "Note that the rules for the ultima storm shield remain unchanged, even though storm shields were updated in the 2020 edition of Codex: Space Marines."

**Comment by Dunamis55** [comment] 2020-10-30 12:33
Duplicate of #8498

**Closed as completed by Dunamis55** 2020-10-30 12:33 UTC
