### ISSUE TITLE
[Anon] Bug report: Imperium - Black Templars.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11026] opened 2022-03-07 17:33 UTC
**File:** Imperium - Black Templars.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** A number of the PL on Marine units in general seem to be off in my version. Primaris Chaplain on a bike is 6PL (should be 7) a Redemptor Dreadnought is 8PL when it should be 9. The same is true for a number of Vehicles that are over costed since the PL updates.

**Comment by Technoblazed** [comment] 2022-03-07 17:51
Duplicate of https://github.com/BSData/wh40k/issues/10952

**Closed as completed by Technoblazed** 2022-03-07 17:51 UTC
