### ISSUE TITLE
scout w/ sniper rifles are 16pts instead of 14pts

### ISSUE THREAD

**Issue by Dusldorf** [BSData/wh40k-9e#11758] opened 2022-08-09 00:08 UTC
**Describe the bug**
scout w/ sniper rifle costs 16pts but should cost 14

**To Reproduce**
look at scout unit entry

**Expected behavior**
scout w/ sniper rifle should cost 16pts

**Device and data (please complete the following information):**
 - OS: windows 10
 - BattleScribe version 2.03.21
 - 40k v.9.6.3

**Additional context**
scouts are ballin'

**Comment by AbonShell** [comment] 2022-08-09 00:09
Duplicate of #11704

**Closed as completed by AbonShell** 2022-08-09 00:09 UTC
