### ISSUE TITLE
Imperium-Agents of Imperium, Voids Men at Arms Points Wrong

### ISSUE THREAD

**Issue by Red93Pichu** [BSData/wh40k-9e#12437] opened 2023-02-03 20:03 UTC
The point cost of Voids Men at Arm should be 40pts/8ppt per model, but the BattleScribe list it as 50pts/10ppt per model

**Comment by AbonShell** [comment] 2023-02-03 20:04
Duplicate of #12436

**Closed as completed by AbonShell** 2023-02-03 20:04 UTC
