### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7442] opened 2020-07-27 06:44 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Points value for thunderfire cannon is wrong.
It should be 140points (85 thunderfire and 55 techmarine gunner with flamer and plasma pistol).
In the app is at 195

**Comment by williamcaw** [comment] 2020-07-27 06:46
dupe of #7439

**Closed as completed** 2020-07-27 06:56 UTC
