### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#298] opened 2017-06-20 15:11 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** Yes

**Description:** Wolf claw pair is 13 pts total. You fixed that weird 6.5 error thanks but now a pair costs 18 pts (9 each) which is incorrect aswell. Please fix

**Comment by penguin20000** [comment] 2017-06-20 15:14
as a unit isn't specified i assume this is a dupe of #295 and i'll close it

**Closed as completed by penguin20000** 2017-06-20 15:14 UTC
Labels: Area: costs, ✔ Res: duplicate, 💾 Cat: Imperium - Space Wolves
