### ISSUE TITLE
[Anon] Bug report: Imperium - Blood Angels.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7508] opened 2020-07-27 15:03 UTC
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** In the Blood Angel's army list the Judiciar is listed as an HQ unit, where in the Edge of Silence book that came with Indomitus he is listed as an Elite

**Comment by Dunamis55** [comment] 2020-07-27 17:13
Duplicate of #7427

**Closed as completed by Dunamis55** 2020-07-27 17:13 UTC
