### ISSUE TITLE
[Anon] Bug report: Imperium - Blood Angels.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7476] opened 2020-07-27 09:35 UTC
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The judiciar is in the HQ section. It should be in the Elites section, due to it being an elite.

**Comment by Gingrel** [comment] 2020-07-27 12:25
Dupe of #7427

**Closed as completed** 2020-07-27 13:21 UTC
