### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9322] opened 2021-01-27 00:03 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Deathguard entry for war gear "Bubonic Axe" is incorrect. Its shows strength +1 when the correct value is now +2

**Comment by Valorcalls** [comment] 2021-01-27 00:04
Duplicate of #9300 #9308

**Closed as completed by Valorcalls** 2021-01-27 00:04 UTC
