### ISSUE TITLE
[Anon] Bug report: Orks.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7462] opened 2020-07-27 08:21 UTC
**File:** Orks.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Boss Nob for boyz is for free. It should cost as a boyz, 8 points.

**Comment by Gingrel** [comment] 2020-07-27 12:23
Dupe of #7422

**Closed as completed** 2020-07-27 13:28 UTC
