### ISSUE TITLE
[Anon] Bug report: Orks.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11524] opened 2022-07-01 05:38 UTC
**File:** Orks.catz

**BattleScribe version:** 2.03.21

**Platform:** Mac

**Dropbox:** No

**Description:** Kustom Jobs are now 0 points in the official Warhammer 40,000 App. Just letting you folks know so that these points are changed to reflect in the BS data too!

**Comment by AbonShell** [comment] 2022-07-01 05:40
Duplicate of #11495

**Closed as completed by AbonShell** 2022-07-01 05:40 UTC
