### ISSUE TITLE
Imperium - Astra Militarum: Narrative some characters are missing access to BRB Crusade Relics

### ISSUE THREAD

**Issue by mattsberg** [BSData/wh40k-9e#12274] opened 2023-01-17 06:50 UTC
**Summary:**
Some character units such as Cadian Command Squad, Militarum Tempestus Command Squad, Platoon Command Squad and Tank Commander are missing the option to select Crusade Relics from the core rulebook (Crusade - BRB).  

These character units have the option to select the Crusade Relics from the Astra Militarum codex and can select options for Battle Traits and Weapon Enhancements from the BRB section, but the Crusade Relics within the BRB section are missing.  

The other character units; Cadian Castellan, Commissar, Regimental Enginseer, Regimental Preacher and Primaris Psyker, are able to select Crusade Relics from the BRB section.

**Steps to replicate:**
1. Click New Roster
2. Click Add Force and select Imperium - Astra Militarum and Order of Battle
3. Click Okay 
4. Click Game Type and then choose Narrative (Crusade)
5. Select one of the affected units (Cadian Command Squad, Militarum Tempestus Command Squad, Platoon Command Squad or Tank Commander)
6. Scroll down to Battle Honors (Crusade - BRB)
7. Crusade Relics are missing from this section

**Expected behavior**
Within the Battle Honors (Crusade - BRB) section there should be a list of Crusade Relics with three sections: Antiquity Relics, Artificer Relics and Legendary Relics.  

To view expected behavior: Select Cadian Castellan and scroll down to Battle Honors in the BRB section, the Crusade Relics are listed there correctly.

**Screenshots**
![missingrelics1](https://user-images.githubusercontent.com/43389568/212828785-934e692e-d942-479e-b149-88a170022663.jpg)
![missingrelic2](https://user-images.githubusercontent.com/43389568/212828791-3cd9d64d-52df-4020-9c92-4f692023de9c.jpg)

**Device and data (please complete the following information):**
 - OS: Windows 10 and Android 13
 - BattleScribe version 2.03.21.166 (Windows 10) and 2.03.25.338 (Android 13)
 - Release version 9.7.1

**Additional context**
N/A

**Comment by WindstormSCR** [comment] 2023-01-25 01:53
Duplicate of #12343

**Closed as completed by WindstormSCR** 2023-01-25 01:53 UTC
Labels: Area: selections, 💾 Cat: Imperium - Astra Militarum, Type: bug, Game Mode: Narrative
