### ISSUE TITLE
8th Adeptus Mechanicus: Special weapons on rangers and vanguards

### ISSUE THREAD

**Issue by robinlindberg** [BSData/wh40k-9e#185] opened 2017-06-18 16:10 UTC
**File/Catalogue:** Adeptus Mechanicus

**BattleScribe version:** 2.01.02

**Platform:** Windows

**Dropbox:** No

**Description:** 

The index states that Skitarii vanguard and ranger units start at 5 models and that at that size up to 2 models may switch to special weapons. I.e. you could have 1 alpha, 2 regular rangers and 2 rangers with Arc Rifles.

This is impossible to at this time. The setting for amount of rangers has a minimum of 4, so if one adds a special weapon ranger, the unit size becomes 6. It is at that point not possible to lower the amount of normal rangers since the minimum value of that control seems to be 4.

If one removes a model from the rooster view you get a warning that you have too few rangers in the squad, although you have 5 if you count them in the rooster view.

Adding special weapons works great for servitors for example, but with rangers and vanguard the cost of the model itself is not included. It is also not counted as a model in the unit, Since I can add infinite amount of special weapons without hitting the max limit for the unit.

**Comment by robinmtb** [comment] 2017-06-18 16:12
Also, it seems like the models with special weapons is not counted into the same amount as the regular when determining Power Level.

**Comment by robinmtb** [comment] 2017-06-18 16:13
Was confused by how servitors include their model cost in the points for the special weapon model and here we do not.

**Comment by Thairne** [comment] 2017-06-18 16:17
.. at which point you can reduce the nubers of vanguards with carbines by one.

**Comment by robinmtb** [comment] 2017-06-18 16:18
Ok. It still works differently for different units. Take a look at servitors. It's very confusing. I'm updating the issue with regards to that.

**Comment by robinmtb** [comment] 2017-06-18 16:20
Also, a ranger is added in the roster list, but you only pay for the weapon pointwise. If you look in the rooster you have 1 more model than you payed for.

**Comment by robinmtb** [comment] 2017-06-18 16:21
And no, I just tried, you cannot reduce the number of vanguards at the point you mentioned...

**Comment by robinmtb** [comment] 2017-06-18 16:32
@Thairne Would you mind removing the tags saying that it is resolved by design etc? Please, Read my updated issue description. This is obviously a bug.

**Closed as completed** 2017-06-18 16:38 UTC
Labels: ✔ Res: invalid, Area: selections, ✔ Res: by design

**Comment by Thairne** [comment] 2017-06-18 19:54
That would be because you're not on the same version of the file on which I already fixed this issue.
