### ISSUE TITLE
Agent of The Imperium -  Add Cartographic Rogue Trader

### ISSUE THREAD

**Issue by Imniskari** [BSData/wh40k-9e#10784] opened 2022-01-01 19:31 UTC
It looks like the War Zone Octarious Book 2 Critical Mass datasheets for the Astra Cryptographica units were never added. 

Specifically it would be nice to have them added to at least the Agents of the Imperium list.

**Comment by AbonShell** [comment] 2022-01-01 19:34
Duplicate of #10741

**Closed as completed by AbonShell** 2022-01-01 19:34 UTC
