### ISSUE TITLE
[Anon] Bug report: Imperium - Blood Angels.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10477] opened 2021-09-23 03:21 UTC
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 9.22.99

**Platform:** Android

**Dropbox:** No

**Description:** Selecting TECHMARINE does not open No Force Orf slot for a unit of SERVITORS (I have checked that this works when applying for another marine detachment I.e iron hands)

**Comment by Mad-Spy** [comment] 2021-09-23 05:46
Duplicate of #10473

**Closed as completed by Mad-Spy** 2021-09-23 05:46 UTC
