### ISSUE TITLE
Guards - Boarding Patrol missing an HQ choice

### ISSUE THREAD

**Issue by JANXOL** [BSData/wh40k-9e#12444] opened 2023-02-04 23:11 UTC
**Describe the bug**
In boarding patrol detachment, one is unable to add tempestus command squad, even though i can find no rule that would prevent it. Normal tempestus infantry is available as normal.

**Comment by AbonShell** [comment] 2023-02-05 00:26
Duplicate of #12435

**Closed as completed by AbonShell** 2023-02-05 00:26 UTC
