### ISSUE TITLE
Imperium - Blood Angels - Missing invader ATV

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8448] opened 2020-10-29 22:11 UTC
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Fast attack section is missing invader ATV. I guess all space marine sections are missing it
Thanks

**Comment by Dunamis55** [comment] 2020-10-30 12:36
Duplicate of #8483

**Closed as completed by Dunamis55** 2020-10-30 12:36 UTC
Labels: Area: selections, 💾 Cat: Imperium - Blood Angels, Type: bug
