### ISSUE TITLE
Imperium - Astra Militarum: Company commander missing PL

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#65] opened 2017-06-16 18:16 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.00

**Platform:** Android

**Dropbox:** No

**Description:** Company Commander had no power points. Should be 3.

**Comment by alphalas** [comment] 2017-06-16 20:49
duplicate of #6

**Closed as completed by alphalas** 2017-06-16 20:49 UTC
Labels: Area: costs, ✔ Res: duplicate, 💾 Cat: Imperium - Astra Militarum
