### ISSUE TITLE
[Anon] Bug report: Imperium - Adeptus Custodes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8109] opened 2020-09-13 17:06 UTC
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** #8094. rolls of a 1 always fail so i dont think that POWER OF THE MACHINE SPIRIT is still in the game at all and the other app has it unlisted from the sheets

**Comment by Mad-Spy** [comment] 2020-09-13 17:15
Duplicate of #8094

**Closed as completed by Mad-Spy** 2020-09-13 17:15 UTC
