### ISSUE TITLE
CSM Fallen weapon options

### ISSUE THREAD

**Issue by fear605** [BSData/wh40k-9e#324] opened 2017-06-21 02:47 UTC
Warhammer 40,000 8th Edition v1.0.9

BattleScribe version: 2.01.

Platform: Windows/Android

Dropbox: No

CSM Fallen weapon options don't include a way to add plasma pistols or more than 2 combi-weapon options/special weapons. 

"Up to four Fallen may choose one of the following options:
-Replace bolt pistol with plasma pistol.
-Replace boltgun with one item from the combi-weapons or Special Weapons lists."
     --Chaos Index pg 14.

The melee options appear to work as expected.

**Comment by FarseerVeraenthis** [comment] 2017-06-21 08:41
Duplicate of #167

**Closed as completed by FarseerVeraenthis** 2017-06-21 08:41 UTC
Labels: ✔ Res: duplicate, Area: selections, 💾 Cat: Chaos - Chaos Space Marines
