### ISSUE TITLE
[Anon] Bug report: Imperium - Deathwatch.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7884] opened 2020-08-09 20:14 UTC
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Primaris Chaplain doesn't have any litanies for the Deathwatch

**Comment by Technoblazed** [comment] 2020-08-10 11:50
Duplicate of https://github.com/BSData/wh40k/issues/7828.

**Closed as completed by Technoblazed** 2020-08-10 11:50 UTC
Labels: ✔ Res: duplicate, Area: text/rule/profile, 💾 Cat: Imperium - Deathwatch, Type: bug
