### ISSUE TITLE
[Anon] Bug report: Imperium - Adepta Sororitas.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7436] opened 2020-07-27 06:09 UTC
**File:** Imperium - Adepta Sororitas.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Storm Bolters are listed as 4 points per wargear option, rather than 3. They should be 3 as per the Munitorum Field Manual page 17.

**Comment by Mad-Spy** [comment] 2020-07-27 06:54
Duplicate of #7434

**Closed as completed by Mad-Spy** 2020-07-27 06:54 UTC
