### ISSUE TITLE
DW sergeant cant take the xeno bane warlord trait

### ISSUE THREAD

**Issue by romakarol** [BSData/wh40k-9e#10619] opened 2021-10-30 06:34 UTC
**Describe the bug**
A DW sergeant upgraded with 'honoured veteran of the watch' should be able to take the 'xeno bane' warlord trait from the octarius supplement as far as I cant tell.

**To Reproduce**
1. Upgrade a sergeant with the honoured veteran of the watch strategem when creating a deathwatch army
2. Xeno hunter isnt listed in the list of strategems he can take. Unlike for example a captain.

**Device and data (please complete the following information):**
 - OS: android
 - BattleScribe version: 40k v9.2.13

**Comment by Technoblazed** [comment] 2021-10-30 06:43
Duplicate of https://github.com/BSData/wh40k/issues/10604

As mentioned in Discord, the WLT can only be taken by your warlord and the `regarded as your WARLORD` part of the strat only applies to the contents of the strat, not which warlord traits they're able to select (ref PA:EW FAQ). 

RAW the deathwatch strat is broken because it doesn't specify where you have to take warlord traits from like all similar strats do.

**Closed as completed by Technoblazed** 2021-10-30 06:43 UTC
