### ISSUE TITLE
Deathwatch Spectrus Killteam - Eliminator’s prices are still old ones

### ISSUE THREAD

**Issue by yurahawk** [BSData/wh40k-9e#10000] opened 2021-06-13 17:27 UTC
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Technoblazed** [comment] 2021-06-13 17:52
Duplicate of #9999. Also woo 10000

**Closed as completed by Technoblazed** 2021-06-13 17:52 UTC
