### ISSUE TITLE
[Anon] Bug report: Imperium - Grey Knights.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8940] opened 2020-12-02 00:37 UTC
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.03.25

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Doomglaive Dreadnought does not appear in the elites slot even when legends/index option is selected

**Comment by Mad-Spy** [comment] 2020-12-02 14:40
Duplicate of #8928

**Closed as completed by Mad-Spy** 2020-12-02 14:40 UTC
