### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#196] opened 2017-06-18 18:57 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** Yes

**Description:** Chaos lord with jump pack second melee weapon options Lightning claw should be the same cost 9 pts. The data file has it at a weird 6.5 pts please fix

**Comment by cartag** [comment] 2017-06-18 19:02
Duplicate of #144

**Closed as completed by cartag** 2017-06-18 19:02 UTC
Labels: ✔ Res: duplicate, 💾 Cat: Chaos - Chaos Space Marines
