### ISSUE TITLE
Astra Millitarum - Heavy Weapons Squad missing Core keyword

### ISSUE THREAD

**Issue by Kelendrad** [BSData/wh40k-9e#12524] opened 2023-02-21 12:37 UTC
**Describe the bug**
heavy Weapons Squad are missing the Core category / keyword

**To Reproduce**
1. Create new Arks of Omen detachment with Astra Millitarum
2. Add Heavy Weapons Squad to your roster
3. View profile of Heavy Weapons Squad
4. Observe issue

**Expected behavior**
In the codex, the Heavy Weapons Squad have the Core keyword

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version v2.03.21.166
 - Release version 319

**Additional context**

**Comment by Mad-Spy** [comment] 2023-02-21 13:51
Duplicate of #12511

**Closed as completed by Mad-Spy** 2023-02-21 13:51 UTC
