### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#93] opened 2017-06-16 23:23 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** No

**Description:** Maulerfiend (Chaos Space Marines) is costed wrong.
Maulerfiend Maulerfists are listed as 16 on battlescribe - should be 0
Maulerfiend Lasher Tendrils are listed as 24 on battlescribe - should be 12

**Comment by cartag** [comment] 2017-06-16 23:41
Duplicate of #90

**Closed as completed by cartag** 2017-06-16 23:41 UTC
Labels: ✔ Res: duplicate, 💾 Cat: Chaos - Chaos Space Marines
