### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8458] opened 2020-10-29 23:00 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Sm: when selecting a squad size of 10 of the heavy intercessors. i am only given a choice of one heavy bolter when it should be 2. just needs a argument at 10 to spawn a 2 box of selection.

**Comment by williamcaw** [comment] 2020-10-30 00:23
#8434 dupe

**Comment by Technoblazed** [comment] 2020-10-30 04:01
Duplicate of https://github.com/BSData/wh40k/issues/8434.

**Closed as completed by Technoblazed** 2020-10-30 04:01 UTC
