### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7950] opened 2020-08-14 16:32 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Ork warboss on bike was NOT deleted by MFM FAQ , the FAQ simply said it was deleted on Page 52 which is only for FORGEWORLD UNITS listing there , and the warboss on bike is NOT a FW unit to begin with hence the FAQ , the unit is still valid for the index entry since 2018 !!! please make this unit valid again in lists as HQ / Warlord !!!

**Comment by DrTobogganMD** [comment] 2020-08-14 22:17
Duplicate of #7949

**Closed as completed by DrTobogganMD** 2020-08-14 22:17 UTC
Labels: ✔ Res: duplicate
