### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#84] opened 2017-06-16 20:14 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** Yes

**Description:** Hallo, chaos space marine - may have special weapons. For 10 or more models in unit may have adition special or heavy weapons. You have only one special and one heavy weapons

**Comment by alphalas** [comment] 2017-06-16 20:56
duplicate of #74

**Closed as completed by alphalas** 2017-06-16 20:56 UTC
Labels: ✔ Res: duplicate, 💾 Cat: Chaos - Chaos Space Marines
