### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9373] opened 2021-02-02 20:08 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Special weapons for Infantry and Veterans both cause an error to pop up if anything but Sniper Rifle is selected.

**Comment by Dunamis55** [comment] 2021-02-02 20:08
Duplicate of #9342

**Closed as completed by Dunamis55** 2021-02-02 20:08 UTC
