### ISSUE TITLE
[Anon] Bug report: Aeldari - Craftworlds.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12476] opened 2023-02-10 10:18 UTC
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** I am making a arks of omen list, I have 2 Farseer in my list as HQ, therefore when I add warlock ( from the Elite slot) it shall not be counted to take any slot in the Elite selection…

But the app keeps warning me about the Elite has too many units… ( I have other 3 units selected in Elite)…

**Comment by AbonShell** [comment] 2023-02-10 10:20
Duplicate of #12475

**Closed as completed by AbonShell** 2023-02-10 10:20 UTC
