### ISSUE TITLE
Tyranids - Genestealer Cults: Relic strat missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12216] opened 2023-01-15 14:46 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Arks of Omen;
- Genestealer Cult
. No option to use the Relic 1CP strat (presumably should be in Stratagems section).
~~. Neophyte Hybrids ; Neophyte Leader ; Melee Weapons - all options should be free (0pts). Specifically, the Power Maul and Power Pick have not been updated to 0pts and still show as 5pts.~~

**Comment by AbonShell** [comment] 2023-01-29 12:00
Duplicate of #12143

**Closed as completed by AbonShell** 2023-01-29 12:00 UTC
Labels: 💾 Cat: Tyranids - Genestealer Cults
