### ISSUE TITLE
[Anon] Bug report: Imperium - Adeptus Custodes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10869] opened 2022-01-28 06:22 UTC
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** Adeptus Custodes had point changes.  See:
https://www.warhammer-community.com/2022/01/21/spread-the-glory-of-the-emperor-with-these-free-adeptus-custodes-points-updates/
For v204 Item Mosacordia is 3-5 points, should be free
Item shield Capt on jetbike down 10 points
Item Trajann Valoris down 10 points
Etc
Etc

**Comment by Technoblazed** [comment] 2022-01-28 06:34
The points are already updated and will be released at the same time as the GT pack, as intended.

**Closed as completed by Technoblazed** 2022-01-28 06:34 UTC
