### ISSUE TITLE
[Anon] Bug report: Imperium - Deathwatch.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11470] opened 2022-06-27 05:05 UTC
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Eliminators with Las Fusil still cost more than Eliminators with Bolt Rifle in the Spectrus Kill Team - this should be adjusted as the Eliminator Squad in Heavy Support got adjusted: the Eliminator with Las Fusils in Spectrus Kill Team should cost as much as the Eliminator with Bolt Rifle does.

**Comment by Mad-Spy** [comment] 2022-06-27 08:24
Duplicate of #11423

**Closed as completed by Mad-Spy** 2022-06-27 08:24 UTC
