### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8238] opened 2020-10-01 16:09 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** temp place holder , request , keywords changing the  power levels and points when attached to a model system when spending command points  overhaul part of #8232

**Comment by Mad-Spy** [comment] 2020-10-01 16:13
Description makes no sense. Closing.

**Comment by williamcaw** [comment] 2020-10-01 16:13
ther is also equipment tags now

**Closed as completed by Mad-Spy** 2020-10-01 16:13 UTC

**Comment by williamcaw** [comment] 2020-10-01 16:14
> Description makes no sense. Closing.

#8232

**Comment by Dunamis55** [comment] 2020-10-01 16:14
If this is related to unreleased content, then it's not a bug that non-public information isn't in the data. Please wait until the books are released and the data devs have had chance to update the data afterwards.
