### ISSUE TITLE
[Anon] Bug report: Tyranids warlord minimum not being fulfilled 

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11454] opened 2022-06-26 12:50 UTC
**File:** Tyranids.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Probably due to the changes to hierarchy for warlords, I get an error message that I need to select a warlord even when one is selected.

**Comment by AbonShell** [comment] 2022-06-26 20:11
Just realized this is a duplicate of #11422

**Closed as completed by AbonShell** 2022-06-26 20:11 UTC
