### ISSUE TITLE
GSC Atalan Jackals w/ Grenade Launcher don't count towards Wolfquad

### ISSUE THREAD

**Issue by ScottSpalding** [BSData/wh40k-9e#10911] opened 2022-02-04 00:58 UTC
**Describe the bug**
When you equip a Jackal with a Grenade Launcher, it stops qualifying for the number of models you need to have for a Wolfquad.

**To Reproduce**
1. Create Atalan Jackal Squad
2. Have 1 AJ w/ GL, 6 AJ w/ SA.
3. Add 2 Wolfquads.
4. Get error, "Too many Wolfquads"

**Expected behavior**
No error should result.

**Device and data (please complete the following information):**
 - OS: Win 10
 - BattleScribe version 2.03.21.166
 - Release version 9.2.26

**Comment by GenWilhelm** [comment] 2022-02-04 11:57
Duplicate of #10895

**Closed as completed by GenWilhelm** 2022-02-04 11:57 UTC
Labels: ✔ Res: duplicate, 💾 Cat: Tyranids - Genestealer Cults, Area: validation, Type: bug
