### ISSUE TITLE
[Anon] Bug report: Tyranids.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12377] opened 2023-01-26 13:13 UTC
**File:** Tyranids.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Tyranids still don't have the option to use the AoO strat heroic support to allow a second hive tyrant

**Comment by Mad-Spy** [comment] 2023-01-26 13:15
Duplicate of #12148

**Closed as completed by Mad-Spy** 2023-01-26 13:15 UTC
