### ISSUE TITLE
Death Guard - Myphitic Blighthauler weapon pts need adjustment

### ISSUE THREAD

**Issue by jollohandley** [BSData/wh40k-9e#8502] opened 2020-10-30 09:23 UTC
**File/Catalogue:** Death Guard

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

**Description:** Myphitic Blighthaulers weapons are wrongly costed. Currently, Multi-Melta is 20pt. Should be 25pt. Missile Launcher is currently 15pt. Should be 20pt.

**Comment by Mad-Spy** [comment] 2020-10-30 09:23
Duplicate of #8454

**Closed as completed by Mad-Spy** 2020-10-30 09:23 UTC
Labels: Area: costs, 💾 Cat: Chaos - Death Guard, Type: bug
