### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9372] opened 2021-02-02 15:58 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Guardsmen with special weapons default to using sniper rifles, and flag roster validation errors when selecting any other special weapon, citing that the selection must be a sniper rifle. This bug is present on both regular guardsmen with special weapons and veterans with special weapons.

**Comment by Dunamis55** [comment] 2021-02-02 15:59
Duplicate of #9342

**Closed as completed by Dunamis55** 2021-02-02 15:59 UTC
