### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11861] opened 2022-09-16 04:34 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** In keeper of secrets, Mesmerising Form  is -1 from hit rolls not just melee hit rolls
Slaanesh Exalted abilities Diaphanous panoply is -1 to wound at range not -1 to hit at range

**Comment by Mad-Spy** [comment] 2022-09-16 05:37
Duplicate of #11859

**Closed as completed by Mad-Spy** 2022-09-16 05:37 UTC
