### ISSUE TITLE
[Anon] Bug report: Imperium - Ultramarines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11810] opened 2022-08-31 08:11 UTC
**File:** Imperium - Ultramarines.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** For the Ironclad Dreadnought, under option 2, the Dreadnought combat weapon w/Heavy Flamer and the Dreadnought combat weapon w/Storm Bolter should instead be a Ironclad combat weapon w/Heavy Flamer and Storm Bolter.

**Comment by Mad-Spy** [comment] 2022-08-31 08:28
Duplicate of #11307

**Closed as completed by Mad-Spy** 2022-08-31 08:28 UTC
