### ISSUE TITLE
[Anon] Bug report: Aeldari - Drukhari.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9691] opened 2021-04-07 01:02 UTC
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Lelith Hesperax is nowhere to be found. When I choose the Cult of Strife she doesn't appear in the avalaible HQ choice.

**Comment by WindstormSCR** [comment] 2021-04-07 03:26
fixed in v112
duplicate of #9677

**Closed as completed by WindstormSCR** 2021-04-07 03:26 UTC
