### ISSUE TITLE
Aeldari - Craftworlds - Hornet weapon selection issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8957] opened 2020-12-04 09:05 UTC
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Hornets (FA) can only be equipped with Shuriken cannons. No other weapon loadouts are available. 

I hope I’m not to dumb to use it.

**Comment by Mad-Spy** [comment] 2020-12-04 09:09
Duplicate of #8929 

It's correct as per the current version of the datasheet, which states it comes with shuriken cannons, but can only swap hornet pulse lasers (which it does not have) for other weapons.

**Closed as completed by Mad-Spy** 2020-12-04 09:09 UTC
Labels: ✔ Res: duplicate, ✔ Res: invalid, Area: selections, 💾 Cat: Aeldari - Craftworlds, Type: bug
