### ISSUE TITLE
[Anon] Bug report: Tyranids - Genestealer Cults.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10898] opened 2022-02-03 01:04 UTC
**File:** Tyranids - Genestealer Cults.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Reductus saboteur cannot take relics. It should have access to the amulet and oppressors bane. Thanks

**Comment by Mad-Spy** [comment] 2022-02-03 10:01
Duplicate of #10885

**Closed as completed by Mad-Spy** 2022-02-03 10:01 UTC
