### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8249] opened 2020-10-02 22:29 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** The Adeptus Astartes, Relic Scorpius Unit is now „Heavy Support“ Not „Elite“ anymore. See Page 42 monitorum field manual

**Comment by Technoblazed** [comment] 2020-10-02 22:41
Duplicate of https://github.com/BSData/wh40k/issues/7808.

MFM changes points for units only, FOS can only be changed through FAQ/Datasheet updates.

**Closed as completed by Technoblazed** 2020-10-02 22:41 UTC
