### ISSUE TITLE
Tyranids: Problem with Warlord Traits?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8880] opened 2020-11-23 22:25 UTC
**File:** Tyranids.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** First Time choose a Warlord and give him a WL Trait ist possible. Nur after changing Something or her a nee WL it isn't possible, to get a WL Trait dir the nee WL. 

Button marks and Charakter is shown AS WL, but after click, nothing Happens. No list of Traits

**Comment by Mad-Spy** [comment] 2020-11-24 11:27
Not sure what the problem is here, exactly. All Warlord related stuff seems to be working properly.

**Comment by Mad-Spy** [comment] 2020-11-26 15:31
No update from OP. Closing.

**Closed as completed by Mad-Spy** 2020-11-26 15:31 UTC
Labels: ✔ Res: no OP clarification, 💾 Cat: Tyranids
