### ISSUE TITLE
Imperium-Deathwatch-Terminator loadouts error

### ISSUE THREAD

**Issue by DenymW** [BSData/wh40k-9e#7326] opened 2020-07-15 12:17 UTC
File/Catalogue:

BattleScribe version: 2.03.

Platform: Windows/iOS/Android/Mac/Linux

Dropbox: Yes/No

Description: Detailed issue description.

Some legal terminator load outs are not supported specifically with equipment trades listed:
*****ISSUE IS WITH THE COMPLETE LOADOUT, SPECIFICALLY CAN'T ADD THE MELTA GUN WITH THE THUNDER HAMMER AND STORM SHIELD***********
Terminator>exchange storm bolter for cyclone missile launcher and storm bolter > exchange power fist for meltagun and powerfist>exchange stormbolter and powerfist for thunderhammer and stormshield >Creates heavy weapon terminator with cyclone missile launcher, meltagun, thunder hammer and storm shield

Terminator>exchange storm bolter for cyclone missile launcher and storm bolter > exchange power fist for meltagun and powerfist>Creates heavy weapon terminator with cyclone missile launcher, storm bolter and meltagun

Terminator> exchange power fist for meltagun and powerfist>exchange stormbolter and powerfist for thunderhammer and stormshield >Creates terminator with meltagun, thunder hammer and storm shield

**Comment by Mad-Spy** [comment] 2020-07-15 12:17
Duplicate of #7325

**Closed as completed by Mad-Spy** 2020-07-15 12:17 UTC
