### ISSUE TITLE
[Anon] Bug report: Imperium - Deathwatch.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7877] opened 2020-08-09 05:43 UTC
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Deathwatch missing special rules for combat doctrines, Storm shield still showing 3++ on non indomitus models, Hellblaster statline not showing when building an intercessor mixed unit even when selected independently. Apologies for the double post.

**Comment by Technoblazed** [comment] 2020-08-10 03:49
Duplicate of https://github.com/BSData/wh40k/issues/7876.

**Closed as completed by Technoblazed** 2020-08-10 03:49 UTC
