### ISSUE TITLE
Tau Sept Issue

### ISSUE THREAD

**Issue by Fuleng** [BSData/wh40k-9e#8046] opened 2020-08-27 15:18 UTC
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** 
The current database does not allow you to choose sept for each unit as it should but rather as a configuration for the detachment. This is very limiting as the codex states clearly that for each unit you can pick a sept regardless of detachment

Please fix this

**Comment by DrTobogganMD** [comment] 2020-08-27 15:25
This will not be implemented in the way you are requesting. The most that will be implemented is a "Mixed Sept" option. We do not allow individual models to have subfactions assigned to them in battlescribe due to how insanely convoluted it would make datafiles.

**Comment by DrTobogganMD** [comment] 2020-08-27 15:26
@amis92 To be RAW, a Mixed Sept option should be added that unhides all Warlord Traits/Relics that are tied to individual septs. If the Mixed Sept is chosen, it's up to the user to validate.  No Sept tenants would be required to be shown because ... you wouldn't get them

**Comment by Mad-Spy** [comment] 2020-08-27 15:27
Every army has the same rules when they have a selectable `<SUBFACTION>` keyword. We don't do it for any of the others, because most people _do_ want to use the Subfaction rules.

**Comment by DrTobogganMD** [comment] 2020-08-27 15:29
@Mad-Spy The issue is in a mixed detachment, relics and WTs are allowed to be mixed. So it is a legal (if very ... unpopular and ineffective) choice.

**Comment by DrTobogganMD** [comment] 2020-08-27 15:38
@Fuleng We discussed this in discord. Tau does not require a sept to be chosen. This represents a mixed sept. When no sept is chosen, no sept traits are displayed (per codex rules) and all Relics are available (per codex rules). At the moment, Warlord traits are still hidden.  That bug will be fixed. Otherwise no changes will be made.

**Comment by amis92** [comment] 2020-08-27 15:43
Closed in favor of #8048

**Closed as completed by amis92** 2020-08-27 15:43 UTC
Labels: ✔ Res: wontfix, Area: selections, 💾 Cat: T'au Empire, Type: bug
