### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11853] opened 2022-09-11 10:41 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Support aces are not selectable on manticores. Tank aces incorrectly require tank commander to be warlord to enable them to be selected. Tank aces don’t appear on tank when selected the tank ace strategm.

**Comment by AbonShell** [comment] 2022-09-11 10:47
Duplicate of #11852

**Closed as completed by AbonShell** 2022-09-11 10:47 UTC
