### ISSUE TITLE
Index - Imperium 1 - Space Wolves Blood Claw Collective

### ISSUE THREAD

**Issue by Gnofry** [BSData/wh40k-9e#561] opened 2017-06-30 01:33 UTC
It seems that the Blood Claws have reverted back to not being collective. Not really necessary to fix, but would be great for printout readability. Having BCx15 is better than BC, BC, BC, etc.

**Comment by flakpanda** [comment] 2017-06-30 05:05
Duplicate of #566 
Sorry, saw/edited that one first.

**Closed as completed by flakpanda** 2017-06-30 05:05 UTC
Labels: ✔ Res: duplicate, Area: view UX, 💾 Cat: Imperium - Space Wolves
