### ISSUE TITLE
[Anon] Bug report: Orks.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7754] opened 2020-07-31 20:58 UTC
**File:** Orks.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Big mek with kustom force field. Points listed as 75 and KFF listed as no points. Model is now 60 points and the KFF is 20 points. Chapter approved points should be used points currently stated are as stated in psychic awakening FAQ.

**Comment by Technoblazed** [comment] 2020-07-31 21:43
Duplicate of https://github.com/BSData/wh40k/issues/7671. The Psychic Awakening: SotB is the newer of the two publications and is therefore the correct points.

https://www.warhammer-community.com/wp-content/uploads/2020/07/kA6zZq83YtZHZ9Ea.pdf

**Closed as completed** 2020-07-31 21:44 UTC
Labels: Area: costs, ✔ Res: invalid, 💾 Cat: Orks, Type: bug
