### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10903] opened 2022-02-03 04:27 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Space wolves wolf guard jump packs are supposed to go up 2pts (from 10 to 12). Most of the other points are updated but this one seems to be missing. Thank you!

**Comment by Mad-Spy** [comment] 2022-02-03 06:40
Duplicate of #10890

**Closed as completed by Mad-Spy** 2022-02-03 06:40 UTC
