### ISSUE TITLE
T'au Empire: Unit slot changes

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7584] opened 2020-07-28 06:26 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Hi, the Y'vahra, like the R'varna, are in the Elites and not anymore in the Fast and Heavy supports.
Thanks!

**Comment by Technoblazed** [comment] 2020-07-28 10:46
Reference https://github.com/BSData/wh40k/issues/7390

**Comment by amis92** [comment] 2020-07-28 14:57
Duplicate of #7519

**Closed as completed by amis92** 2020-07-28 14:57 UTC
Labels: Area: selections, 💾 Cat: T'au Empire, Type: bug
