### ISSUE TITLE
[Anon] Bug report: Necrons.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8070] opened 2020-09-02 04:49 UTC
**File:** Necrons.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** no force org is broken for super heavy aux and super heavy for the cryptohralls

**Comment by Mad-Spy** [comment] 2020-09-02 07:13
This report is useless as it contains no details of what the problem is. Closing.

**Closed as completed by Mad-Spy** 2020-09-02 07:13 UTC
