### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#212] opened 2017-06-19 01:44 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox:** No

**Description:** Unable to get legal infantry squad when selecting a heavy weapons squad. Always shows either too many or not enough guardsmen selections regardless of the amount of guardsmen you put in.

**Comment by raptor1770** [comment] 2017-06-19 03:15
Cannot recreate issue. Infantry squad selection seems to be functioning correctly.

**Comment by blackrabbit84** [comment] 2017-06-19 05:53
I can confirm I'm also experiencing the same issue. If I take an infantry squad with a heavy weapon, I get the error that the squad contains "1 too many selections from guardsmen" when reduce the amount of guardsmen by , I get the error "squad must have 1 more selections from guardsmen". Seems to happen with veterans too.

**Comment by GenWilhelm** [comment] 2017-06-19 06:08
This was fixed in 7595e59fe3bbfed13917d4aa6ef7e5c370ca2671. It will be out with the next release (Astra Miliatrum v12) in a few hours.

**Closed as completed by GenWilhelm** 2017-06-19 06:08 UTC
Labels: ✔ Res: deprecated, 💾 Cat: Imperium - Astra Militarum, Area: validation
