### ISSUE TITLE
[Anon] Bug report: Imperium - Deathwatch.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7615] opened 2020-07-28 12:08 UTC
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Missing Indomitus models 
FAQ source: 
"The <Chapter> Keyword Indomitus has been released and the forces of the Adeptus Astartes have been reinforced. On the datasheets for the new miniatures  within  The Edge of Silence, there is the  <Chapter> Faction keyword, meaning these units belong to Space Marine Chapters from  Codex:  Space  Marines. You can, however, take these units as part of another Space Marine Chapter not found within that publication. To do so, replace the  <Chapter> keyword in every instance on that unit’s datasheet with  Blood Angels  (or the keyword of a Blood Angels successor Chapter, e.g. Flesh Tearers),  Dark Angels  (or the keyword of a Dark Angels successor Chapter, e.g.  Angels of Absolution),  Deathwatch or  Space Wolves. For example, if you include an Assault Intercessors unit and you decide it is from the Blood Angels Chapter, its keyword becomes  Blood Angels."

**Comment by Mad-Spy** [comment] 2020-07-28 12:31
Duplicate of #7496

**Closed as completed by Mad-Spy** 2020-07-28 12:31 UTC
