### ISSUE TITLE
[Anon] Bug report: Necrons.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12478] opened 2023-02-10 14:14 UTC
**File:** Necrons.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** I have 2 separate Skorpekh Destroyer units. So I should get 2 no org Plasmacytes. But when I add 2, it says that I have 1 to many (maximum 1).

**Comment by Mad-Spy** [comment] 2023-02-10 14:16
duplicate of #12379

**Closed as completed by Mad-Spy** 2023-02-10 14:16 UTC
