### ISSUE TITLE
Drukhari: Scourge PL costs incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12601] opened 2023-03-16 17:36 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Drukhari Scourge PL costs are incorrect.
Currently [Aeldar v158, Drukhari v150], scourges are PL6 for 5, and PL10 for 10, both in Drukhari and Ynarri lists.

They should be 5/8PL for 4/10models (per codex and 2022 PL update) for Drukhari, and 6/10PL for Ynarri only (like Incubi, they are +1PL for 5, +2 PL for 10 in Ynarri units)

**Comment by FarseerVeraenthis** [comment] 2023-03-17 21:15
Functioning as intended in Drukhari
![image](https://user-images.githubusercontent.com/23246922/226052954-df916930-2cae-4320-aba0-6078e583a6d9.png)

**Comment by FarseerVeraenthis** [comment] 2023-03-17 21:23
fixed in next release :-) a single conditional was not focused correctly...
![image](https://user-images.githubusercontent.com/23246922/226056155-c27c09de-e56c-4160-b1b9-f3c5b80bdc27.png)

**Closed as completed** 2023-03-17 21:24 UTC
Labels: Area: costs, 💾 Cat: Aeldari - Drukhari, Type: bug
