### ISSUE TITLE
[Anon] Bug report: Imperium - Inquisition.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8895] opened 2020-11-25 18:53 UTC
**File:** Imperium - Inquisition.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** The Quad Heavy Bolters on the Inquisition Land Raider Prometheus are still listed as 60 points each however they should now be free as their cost has been combined with the base unit cost.

**Comment by williamcaw** [comment] 2020-11-25 19:41
it has not passed #8847

**Comment by Technoblazed** [comment] 2020-11-26 09:36
Dupe of https://github.com/BSData/wh40k/issues/8847

**Closed as completed by Technoblazed** 2020-11-26 09:36 UTC
