### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11003] opened 2022-02-25 13:03 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Power Rating Update 2022 has not been implemented for Astra Militarum units.

**Comment by Mad-Spy** [comment] 2022-02-25 13:10
Duplicate of #10922

**Closed as completed by Mad-Spy** 2022-02-25 13:10 UTC
