### ISSUE TITLE
[Anon] Bug report: Aeldari - Drukhari.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9714] opened 2021-04-11 12:33 UTC
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 9.01.26

**Platform:** Android

**Dropbox:** No

**Description:** "Drukhari Reavers" point cost should be 20, not 10

**Comment by Valorcalls** [comment] 2021-04-11 12:36
Duplicate of #9710

**Closed as completed by Valorcalls** 2021-04-11 12:36 UTC
