### ISSUE TITLE
[Anon] Bug report: Imperium - Sisters of Silence.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10287] opened 2021-08-16 03:42 UTC
**File:** Imperium - Sisters of Silence.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Battlescribe - Space Marine: Eradicator Squad (7PL, 135Pts/45Pts per model)

9th Edition Codex, Pg 175 (6PL), Pg 205 (40Pts/Model)

**Comment by Technoblazed** [comment] 2021-08-16 03:49
Dupe of https://github.com/BSData/wh40k/issues/10288

**Closed as completed by Technoblazed** 2021-08-16 03:49 UTC
