### ISSUE TITLE
[Anon] Bug report: Orks.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12171] opened 2023-01-15 03:04 UTC
**File:** Orks.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** No heroic stratagem in configuration for the warbosses

Beastboss on squigg issues/not showing unless ghaz also in army when trying to select warlord and relic stratgems

**Comment by haroldl** [comment] 2023-01-15 06:08
It is a Requisition Stratagem named "Heroic Support" which allows you to change the limit for a Detachment Ability from 1 to 2 for including units. Since "I'm Da Boss!" is a Detachment Ability (Codex: Orks page 51) there should be a way to use this stratagem to have 2 Warboss or Deffkilla Wartrikes in an Arks of Omen game type.

**Comment by Mad-Spy** [comment] 2023-01-15 11:20
Duplicate of #12170

**Closed as completed by Mad-Spy** 2023-01-15 11:20 UTC
