### ISSUE TITLE
[Anon] Bug report: Imperium - Blood Angels.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12338] opened 2023-01-22 19:25 UTC
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 9.02.02

**Platform:** Windows

**Dropbox:** Yes

**Description:** When selected to be the Warlord the Librarian Dreadnoughts Warlord Trait options don't appear when Arks of Omen is selected to be the game type.

**Comment by Mad-Spy** [comment] 2023-01-22 19:26
Duplicate of #12242

**Closed as completed by Mad-Spy** 2023-01-22 19:26 UTC
