### ISSUE TITLE
[Anon] Bug report: Chaos - Death Guard.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9299] opened 2021-01-24 00:45 UTC
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 9.01.12

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Biologus putrefier is missing. 

Thanks for updating the whole DG codex so fast!!! That was wicked to have.

**Comment by Valorcalls** [comment] 2021-01-24 00:46
Duplicate of #9296

**Closed as completed by Valorcalls** 2021-01-24 00:46 UTC
