### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8234] opened 2020-10-01 04:07 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** unable to find relic upgrades on some weapons ex. sun wrath pistol

**Comment by Valorcalls** [comment] 2020-10-01 04:55
Duplicate of #8229

**Closed as completed by Valorcalls** 2020-10-01 04:55 UTC
Labels: ✔ Res: duplicate
