### ISSUE TITLE
Manticore Heavy Bolter & Heavy Flamer options are priced incorrectly

### ISSUE THREAD

**Issue by Dusldorf** [BSData/wh40k-9e#7512] opened 2020-07-27 16:02 UTC
**File/Catalogue:** Warhammer 40,000 v9.0.0

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The Manticore's Heavy Bolter currently costs 8pts, and its Heavy Flamer currently costs 14pts, but CA2020 indicates that both should cost 15.

**Comment by williamcaw** [comment] 2020-07-27 18:04
dupe of #7457

**Closed as completed** 2020-07-28 01:39 UTC
Labels: Area: costs, 💾 Cat: Imperium - Astra Militarum, Type: bug
