### ISSUE TITLE
[Anon] Bug report: Necrons.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12520] opened 2023-02-20 19:34 UTC
**File:** Necrons.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** No more than one canoptek plasmacyte can be included in No Force Org Slot, even if there are enough Destroyer Cult units for them.

**Comment by Mad-Spy** [comment] 2023-02-20 21:16
Duplicate of #12379

**Closed as completed by Mad-Spy** 2023-02-20 21:16 UTC
