### ISSUE TITLE
[Anon] Bug report: Imperium - Grey Knights.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11430] opened 2022-06-25 06:40 UTC
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 9.04.01

**Platform:** Android

**Dropbox:** No

**Description:** Hi,

Shield of Humanity does not give a Warlord trait.

**Comment by Mad-Spy** [comment] 2022-06-25 09:17
Duplicate of #11425

**Closed as completed by Mad-Spy** 2022-06-25 09:17 UTC
