### ISSUE TITLE
Imperium - Blood Angels: Blood Talon cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7691] opened 2020-07-30 01:39 UTC
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** According to the Field Manual, Blood Talons are supposed to be 35 not 45.

**Comment by DrTobogganMD** [comment] 2020-07-30 19:23
Corrected cost.

**Comment by DrTobogganMD** [comment] 2020-07-30 19:48
Duplicate of #7582

**Closed as completed by DrTobogganMD** 2020-07-30 19:48 UTC
Labels: Area: costs, ✔ Res: duplicate, 💾 Cat: Imperium - Blood Angels
