### ISSUE TITLE
Servitor No Force Org Slot (Adeptus Astartes (Blood Angels))

### ISSUE THREAD

**Issue by SuperCaffeineDude** [BSData/wh40k-9e#10514] opened 2021-10-04 07:10 UTC
When a techmarine (keyword) unit is present, a servitor squad can be taken without taking up the elite slot due to the Mindlock ability. I would presume the techmarine (primaris/non-primaris) should allow a +1 unit of servitors to be taken in the No Force Org Slot

**Comment by Mad-Spy** [comment] 2021-10-04 08:04
Duplicate of #10473

**Closed as completed by Mad-Spy** 2021-10-04 08:04 UTC
