### ISSUE TITLE
Imperium - Astra Militarum: Special weapons sniper rifle bug

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9366] opened 2021-02-01 09:47 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Astra Militarum infantry squad - insists that special guardsman with special weapon must take a sniper rifle, shows roster error on any other choice

**Comment by Mad-Spy** [comment] 2021-02-01 09:58
Duplicate of #9342

**Closed as completed by Mad-Spy** 2021-02-01 09:58 UTC

**Comment by Deecee29** [comment] 2021-02-02 14:28
This is also a bug on iOS
