### ISSUE TITLE
[Anon] Bug report: Tyranids - Genestealer Cults.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12497] opened 2023-02-16 05:29 UTC
**File:** Tyranids - Genestealer Cults.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Arks of omen detachment only allows a maximum of 6 choices when selecting compulsory type as elite.

**Comment by Mad-Spy** [comment] 2023-02-16 09:51
Sounds like it's working as intended then. Closing.

**Closed as completed by Mad-Spy** 2023-02-16 09:51 UTC
