### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7569] opened 2020-07-28 00:49 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The manticore entry for astra militarum still uses the old points for the heavy bolter and heavy flamer at 8 and 14 points respectively when they should both be 15 points each

**Comment by williamcaw** [comment] 2020-07-28 01:45
dupe of #7457

**Closed as completed** 2020-07-28 02:09 UTC
