### ISSUE TITLE
Chapter command WLTs missing (and some relics)

### ISSUE THREAD

**Issue by GuillermoDiazGarcia** [BSData/wh40k-9e#8500] opened 2020-10-30 09:05 UTC
**File/Catalogue:** Deathwatch

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** 
All the chapter command-related warlord traits are missing in the deathwatch (and probably other chapters). Also, Teeth of Terra as an option is missing in the apothecary, but he does have a chainsword

**Comment by Technoblazed** [comment] 2020-10-31 05:31
Chapter command is a dupe of https://github.com/BSData/wh40k/issues/8471. 

Teeth of Terra missing is something that @acebaur needs to fix in the lib.

**Closed as completed** 2020-11-01 04:35 UTC
Labels: 💾 Cat: Imperium - Deathwatch, Area: validation, Type: bug
