### ISSUE TITLE
[Anon] Bug report: Imperium - Blood Angels.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8459] opened 2020-10-29 23:01 UTC
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Sanguinary Priest is missing Hero of the Chapter option

**Comment by Technoblazed** [comment] 2020-10-30 04:09
Duplicate of https://github.com/BSData/wh40k/issues/8420

**Closed as completed by Technoblazed** 2020-10-30 04:09 UTC
Labels: ✔ Res: duplicate
