### ISSUE TITLE
Weapons selection dkok Astra militarum 

### ISSUE THREAD

**Issue by Foxen1** [BSData/wh40k-9e#12134] opened 2023-01-14 12:03 UTC
Death korps of krieg infantry squad is allowed 2 of the same special weapons (excluding plasma) according to the new codex but BS gives me an error when selecting 2 meltas in the same squad.

**Comment by Mad-Spy** [comment] 2023-01-14 13:33
Duplicate of #12099

**Closed as completed by Mad-Spy** 2023-01-14 13:33 UTC
