### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11111] opened 2022-04-01 08:31 UTC
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** You cannot make a Company Champion a Chapter Champion in Black Templars.

**Comment by Mad-Spy** [comment] 2022-04-01 08:49
Duplicate of #11112

**Closed as completed by Mad-Spy** 2022-04-01 08:49 UTC
